// Generated by ankh-types. Do not edit by hand.

export type DeviceAuthGrantId = string;

export type DeviceSessionId = string;

export type InviteId = string;

export type NamespaceId = string;

export type NamespaceKind = "user" | "org";

export type OrgId = string;

export type OrgInviteId = string;

export type OrgRole = "owner" | "admin" | "member";

export type SessionId = string;

export type SysadminId = string;

export type SysadminTokenId = string;

export type TokenId = string;

export type UserId = string;

export type DevicePlatform = string;

export type UserInfo = {
  /**
   * User's unique username.
   */
  username: string;
  /**
   * User email address.
   */
  email: string;
  /**
   * Whether the email has been verified.
   */
  email_verified: boolean;
  /**
   * Whether the account is currently waitlisted.
   */
  waitlisted: boolean;
};

export type AuthSuccess = {
  /**
   * Authenticated user info.
   */
  user: UserInfo;
};

export type AuthMeResponse = {
  /**
   * Current user if a web session is authenticated.
   */
  user: UserInfo | null;
};

export type SignupRequest = {
  /**
   * Requested username.
   */
  username: string;
  /**
   * User email address.
   */
  email: string;
  /**
   * User password.
   */
  password: string;
  /**
   * Optional account invite token.
   */
  invite_token: string | null;
  /**
   * Optional organization invite token.
   */
  org_invite_token: string | null;
};

export type LoginRequest = {
  /**
   * Email address or username.
   */
  email: string;
  /**
   * User password.
   */
  password: string;
};

export type WaitlistStatusResponse = {
  /**
   * Whether waitlist mode is currently enabled.
   */
  waitlist_enabled: boolean;
};

export type VerificationRequest = {
  /**
   * Raw verification token.
   */
  token: string;
};

export type ResendVerificationRequest = {
  /**
   * Email address to send a verification link to.
   */
  email: string;
};

export type ForgotPasswordRequest = {
  /**
   * Email address to send a reset link to.
   */
  email: string;
};

export type ValidateResetTokenRequest = {
  /**
   * Raw password reset token.
   */
  token: string;
};

export type ValidateResetTokenResponse = {
  /**
   * Email address associated with the reset token.
   */
  email: string;
};

export type PasswordResetRequest = {
  /**
   * Raw password reset token.
   */
  token: string;
  /**
   * New password.
   */
  password: string;
};

export type OrgInfo = {
  /**
   * Organization ID, or namespace ID for personal organizations.
   */
  id: string;
  /**
   * Organization name.
   */
  name: string;
  /**
   * Optional display name.
   */
  display_name: string | null;
  /**
   * User's role in this organization.
   */
  role: string;
  /**
   * Whether this is a personal organization.
   */
  is_personal: boolean;
};

export type CreateOrgInput = {
  /**
   * Organization name.
   */
  name: string;
  /**
   * Optional display name.
   */
  display_name: string | null;
};

export type OrgMemberInfo = {
  /**
   * User ID.
   */
  user_id: string;
  /**
   * Username.
   */
  username: string;
  /**
   * Role in the organization.
   */
  role: string;
};

export type MemberInfo = {
  /**
   * User ID.
   */
  user_id: string;
  /**
   * Username.
   */
  username: string;
  /**
   * Email address.
   */
  email: string;
  /**
   * Role in the organization.
   */
  role: string;
};

export type InviteInfo = {
  /**
   * Invite ID.
   */
  id: string;
  /**
   * Email address invited.
   */
  email: string;
  /**
   * When the invite was created.
   */
  created_at: string;
  /**
   * When the invite expires.
   */
  expires_at: string;
};

export type OrgInviteDetails = {
  /**
   * Organization name.
   */
  org_name: string;
  /**
   * Organization display name.
   */
  org_display_name: string | null;
  /**
   * Email the invite was sent to.
   */
  invite_email: string;
};

export type AcceptOrgInviteResponse = {
  /**
   * Organization joined by accepting the invite.
   */
  org: OrgInfo;
};

export type DeviceSessionInfo = {
  /**
   * Session ID.
   */
  id: string;
  /**
   * Device name.
   */
  device_name: string;
  /**
   * Platform identifier.
   */
  platform: DevicePlatform;
  /**
   * Status: active, revoked, or expired.
   */
  status: string;
  /**
   * When the session was created.
   */
  created_at: string;
  /**
   * When the session was last used.
   */
  last_used_at: string;
  /**
   * When the session expires.
   */
  expires_at: string;
};

export type CreateDeviceSessionResponse = {
  /**
   * Raw bearer token returned once.
   */
  token: string;
  /**
   * Device label associated with the session.
   */
  device_name: string;
  /**
   * When the token expires.
   */
  expires_at: string;
};

export type DeviceAuthorizationRequest = {
  /**
   * PKCE S256 code challenge.
   */
  code_challenge: string;
  /**
   * Loopback redirect port.
   */
  redirect_port: number;
  /**
   * Caller-provided state echoed back to the loopback callback.
   */
  state: string;
  /**
   * Human-readable device name.
   */
  device_name: string;
  /**
   * Platform identifier supplied by the device client.
   */
  platform: DevicePlatform;
};

export type DeviceAuthorizationResponse = {
  /**
   * Raw one-time authorization code.
   */
  code: string;
  /**
   * Loopback callback URL.
   */
  callback_url: string;
  /**
   * When the grant expires.
   */
  expires_at: string;
};

export type DeviceTokenRequest = {
  /**
   * Raw one-time authorization code.
   */
  code: string;
  /**
   * PKCE verifier corresponding to the authorization challenge.
   */
  code_verifier: string;
};

export type DeviceTokenResponse = {
  /**
   * Raw bearer token returned once.
   */
  token: string;
  /**
   * Human-readable device name.
   */
  device_name: string;
  /**
   * Platform identifier stored for the session.
   */
  platform: DevicePlatform;
  /**
   * When the device session expires.
   */
  expires_at: string;
};

export type AdminLoginRequest = {
  /**
   * Sysadmin email address.
   */
  email: string;
  /**
   * Sysadmin password.
   */
  password: string;
};

export type SysadminIdentity = {
  /**
   * Sysadmin ID.
   */
  id: string;
  /**
   * Sysadmin email address.
   */
  email: string;
};

export type LoginResponse = {
  /**
   * Bearer token to use for authenticated requests.
   */
  token: string;
  /**
   * Token expiration timestamp.
   */
  expires_at: string;
  /**
   * Authenticated sysadmin identity.
   */
  sysadmin: SysadminIdentity;
};

export type SysadminSummary = {
  /**
   * Sysadmin ID.
   */
  id: string;
  /**
   * Sysadmin email address.
   */
  email: string;
  /**
   * When the sysadmin was created.
   */
  created_at: string;
  /**
   * When the sysadmin last logged in, if ever.
   */
  last_login_at: string | null;
};

export type ListSysadminsResponse = {
  /**
   * List of sysadmins.
   */
  sysadmins: Array<SysadminSummary>;
  /**
   * Cursor for fetching the next page, if more results exist.
   */
  next_cursor: string | null;
};

export type WhoamiResponse = {
  /**
   * Authenticated sysadmin info.
   */
  sysadmin: SysadminSummary;
};

export type UserSummary = {
  /**
   * User ID.
   */
  id: string;
  /**
   * User's unique username.
   */
  username: string;
  /**
   * User email address.
   */
  email: string;
  /**
   * When the user was created.
   */
  created_at: string;
  /**
   * When the email was verified, if ever.
   */
  verified_at: string | null;
};

export type ListUsersResponse = {
  /**
   * List of users.
   */
  users: Array<UserSummary>;
  /**
   * Cursor for fetching the next page, if more results exist.
   */
  next_cursor: string | null;
};

export type UserDetail = {
  /**
   * User ID.
   */
  id: string;
  /**
   * User's unique username.
   */
  username: string;
  /**
   * User email address.
   */
  email: string;
  /**
   * When the user was created.
   */
  created_at: string;
  /**
   * When the email was verified, if ever.
   */
  verified_at: string | null;
  /**
   * Most recent session activity, if any sessions exist.
   */
  last_session_at: string | null;
};

export type ReleaseUserRequest = {
  /**
   * User ID to release.
   */
  id: string | null;
  /**
   * User email to release.
   */
  email: string | null;
};

export type ReleaseUserResponse = {
  /**
   * User email address.
   */
  email: string;
};

export type InviteUserRequest = {
  /**
   * User email to invite.
   */
  email: string;
};

export type InviteAction = "invited" | "released" | "already_active";

export type InviteUserResponse = {
  /**
   * User email address.
   */
  email: string;
  /**
   * Action taken for the invite request.
   */
  action: InviteAction;
};

export type SessionSummary = {
  /**
   * Session ID.
   */
  id: string;
  /**
   * User ID that owns this session.
   */
  user_id: string;
  /**
   * User email.
   */
  user_email: string;
  /**
   * Computed status based on revoked_at and expires_at.
   */
  status: string;
  /**
   * When the session was created.
   */
  created_at: string;
  /**
   * When the session was last used.
   */
  last_seen_at: string;
  /**
   * When the session expires.
   */
  expires_at: string;
  /**
   * When the session was revoked, if ever.
   */
  revoked_at: string | null;
};

export type ListSessionsResponse = {
  /**
   * List of sessions.
   */
  sessions: Array<SessionSummary>;
  /**
   * Cursor for fetching the next page, if more results exist.
   */
  next_cursor: string | null;
};

export type DeviceSessionSummary = {
  /**
   * Session ID.
   */
  id: string;
  /**
   * User ID that owns this session.
   */
  user_id: string;
  /**
   * User email.
   */
  user_email: string;
  /**
   * Device name for the session.
   */
  device_name: string;
  /**
   * Platform identifier.
   */
  platform: string;
  /**
   * Computed status based on revoked_at and expires_at.
   */
  status: string;
  /**
   * When the session was created.
   */
  created_at: string;
  /**
   * When the session was last used.
   */
  last_used_at: string;
  /**
   * When the session expires.
   */
  expires_at: string;
  /**
   * When the session was revoked, if ever.
   */
  revoked_at: string | null;
};

export type ListDeviceSessionsResponse = {
  /**
   * List of device sessions.
   */
  sessions: Array<DeviceSessionSummary>;
  /**
   * Cursor for fetching the next page, if more results exist.
   */
  next_cursor: string | null;
};

export type OrgSummary = {
  /**
   * Organization ID.
   */
  id: string;
  /**
   * Organization name.
   */
  name: string;
  /**
   * Display name.
   */
  display_name: string | null;
  /**
   * When the org was created.
   */
  created_at: string;
};

export type ListOrgsResponse = {
  /**
   * List of organizations.
   */
  orgs: Array<OrgSummary>;
  /**
   * Cursor for fetching the next page.
   */
  next_cursor: string | null;
};

export type OrgDetail = {
  /**
   * Organization ID.
   */
  id: string;
  /**
   * Organization name.
   */
  name: string;
  /**
   * Display name.
   */
  display_name: string | null;
  /**
   * User who created the org, if the creator still exists.
   */
  created_by: string | null;
  /**
   * Namespace ID owned by the org.
   */
  namespace_id: string;
  /**
   * Namespace status.
   */
  namespace_status: string;
  /**
   * Namespace generation.
   */
  namespace_gen: bigint;
  /**
   * When the org was created.
   */
  created_at: string;
  /**
   * When the org was last updated.
   */
  updated_at: string;
};

export type CreateOrgRequest = {
  /**
   * Organization name.
   */
  name: string;
  /**
   * Optional display name.
   */
  display_name: string | null;
  /**
   * User ID who will be the owner.
   */
  owner_id: string;
};

export type UpdateOrgRequest = {
  /**
   * New display name.
   */
  display_name: string | null;
};

export type OrgMember = {
  /**
   * User ID.
   */
  user_id: string;
  /**
   * Username.
   */
  username: string;
  /**
   * Email address.
   */
  email: string;
  /**
   * Role in the organization.
   */
  role: string;
  /**
   * When the member was added.
   */
  created_at: string;
};

export type ListMembersResponse = {
  /**
   * List of members.
   */
  members: Array<OrgMember>;
};

export type AddMemberRequest = {
  /**
   * User ID to add.
   */
  user_id: string;
  /**
   * Role for the new member.
   */
  role: string;
};

export type SetRoleRequest = {
  /**
   * New role.
   */
  role: string;
};

export type TransferOwnershipRequest = {
  /**
   * User ID of new owner.
   */
  new_owner_id: string;
};

export type OrgInvite = {
  /**
   * Invite ID.
   */
  id: string;
  /**
   * Invited email.
   */
  email: string;
  /**
   * When the invite was created.
   */
  created_at: string;
  /**
   * When the invite expires.
   */
  expires_at: string;
  /**
   * When the invite was accepted, if ever.
   */
  accepted_at: string | null;
  /**
   * When the invite was revoked, if ever.
   */
  revoked_at: string | null;
};

export type ListOrgInvitesResponse = {
  /**
   * List of invites.
   */
  invites: Array<OrgInvite>;
};

export type CreateOrgInviteRequest = {
  /**
   * Email to invite.
   */
  email: string;
};

export type CreateOrgInviteResponse = {
  /**
   * Invite ID.
   */
  id: string;
  /**
   * Invited email.
   */
  email: string;
  /**
   * Raw token returned only on creation.
   */
  token: string;
};

export type SettingsResponse = {
  /**
   * Whether waitlist mode is enabled.
   */
  waitlist_enabled: boolean;
};

export type WaitlistSettingsRequest = {
  /**
   * Desired waitlist enablement.
   */
  enabled: boolean;
};

export type NamespaceStatusResponse = {
  /**
   * Namespace ID.
   */
  id: string;
  /**
   * Namespace status.
   */
  status: string;
  /**
   * Namespace generation after the mutation.
   */
  gen: bigint;
};
