//! TypeScript declaration generation for shared Ankh DTOs.

use std::{fs, io, path::Path};

use dprint_plugin_typescript::{
    FormatTextOptions, configuration::ConfigurationBuilder, format_text,
};
use ts_rs::{Config, TS};

use crate::{
    DeviceAuthGrantId, DeviceSessionId, InviteId, NamespaceId, NamespaceKind, OrgId, OrgInviteId,
    OrgRole, SessionId, SysadminId, SysadminTokenId, TokenId, UserId,
    admin::{
        AddMemberRequest, AdminLoginRequest, CreateOrgInviteRequest, CreateOrgInviteResponse,
        CreateOrgRequest, DeviceSessionSummary, InviteAction, InviteUserRequest,
        InviteUserResponse, ListDeviceSessionsResponse, ListMembersResponse,
        ListOrgInvitesResponse, ListOrgsResponse, ListSessionsResponse, ListSysadminsResponse,
        ListUsersResponse, LoginResponse, NamespaceStatusResponse, OrgDetail, OrgInvite, OrgMember,
        OrgSummary, ReleaseUserRequest, ReleaseUserResponse, SessionSummary, SetRoleRequest,
        SettingsResponse, SysadminIdentity, SysadminSummary, TransferOwnershipRequest,
        UpdateOrgRequest, UserDetail, UserSummary, WaitlistSettingsRequest, WhoamiResponse,
    },
    public::{
        AcceptOrgInviteResponse, AuthMeResponse, AuthSuccess, CreateDeviceSessionResponse,
        CreateOrgInput, DeviceAuthorizationRequest, DeviceAuthorizationResponse, DevicePlatform,
        DeviceSessionInfo, DeviceTokenRequest, DeviceTokenResponse, ForgotPasswordRequest,
        InviteInfo, LoginRequest as PublicLoginRequest, MemberInfo, OrgInfo, OrgInviteDetails,
        OrgMemberInfo, PasswordResetRequest, ResendVerificationRequest, SignupRequest, UserInfo,
        ValidateResetTokenRequest, ValidateResetTokenResponse, VerificationRequest,
        WaitlistStatusResponse,
    },
};

/// Relative path to the generated declaration file consumed by `@ankh/types`.
pub const TYPESCRIPT_DECLARATION_RELATIVE_PATH: &str = "frontend/packages/types/src/generated.d.ts";

/// Header used for generated TypeScript declaration files.
pub const TYPESCRIPT_DECLARATION_HEADER: &str =
    "// Generated by ankh-types. Do not edit by hand.\n\n";

/// Generate the complete TypeScript declaration file.
#[must_use]
pub fn typescript_declarations() -> String {
    let mut output = String::from(TYPESCRIPT_DECLARATION_HEADER);
    output.push_str(typescript_declaration_body().as_str());
    format_typescript_declarations(output.as_str(), TYPESCRIPT_DECLARATION_RELATIVE_PATH)
        .expect("format generated TypeScript declarations")
}

/// Generate the Ankh-owned declaration body without the file header.
#[must_use]
pub fn typescript_declaration_body() -> String {
    let cfg = Config::default();
    let mut output = String::new();

    push::<DeviceAuthGrantId>(&mut output, &cfg);
    push::<DeviceSessionId>(&mut output, &cfg);
    push::<InviteId>(&mut output, &cfg);
    push::<NamespaceId>(&mut output, &cfg);
    push::<NamespaceKind>(&mut output, &cfg);
    push::<OrgId>(&mut output, &cfg);
    push::<OrgInviteId>(&mut output, &cfg);
    push::<OrgRole>(&mut output, &cfg);
    push::<SessionId>(&mut output, &cfg);
    push::<SysadminId>(&mut output, &cfg);
    push::<SysadminTokenId>(&mut output, &cfg);
    push::<TokenId>(&mut output, &cfg);
    push::<UserId>(&mut output, &cfg);
    push::<DevicePlatform>(&mut output, &cfg);

    push::<UserInfo>(&mut output, &cfg);
    push::<AuthSuccess>(&mut output, &cfg);
    push::<AuthMeResponse>(&mut output, &cfg);
    push::<SignupRequest>(&mut output, &cfg);
    push::<PublicLoginRequest>(&mut output, &cfg);
    push::<WaitlistStatusResponse>(&mut output, &cfg);
    push::<VerificationRequest>(&mut output, &cfg);
    push::<ResendVerificationRequest>(&mut output, &cfg);
    push::<ForgotPasswordRequest>(&mut output, &cfg);
    push::<ValidateResetTokenRequest>(&mut output, &cfg);
    push::<ValidateResetTokenResponse>(&mut output, &cfg);
    push::<PasswordResetRequest>(&mut output, &cfg);
    push::<OrgInfo>(&mut output, &cfg);
    push::<CreateOrgInput>(&mut output, &cfg);
    push::<OrgMemberInfo>(&mut output, &cfg);
    push::<MemberInfo>(&mut output, &cfg);
    push::<InviteInfo>(&mut output, &cfg);
    push::<OrgInviteDetails>(&mut output, &cfg);
    push::<AcceptOrgInviteResponse>(&mut output, &cfg);
    push::<DeviceSessionInfo>(&mut output, &cfg);
    push::<CreateDeviceSessionResponse>(&mut output, &cfg);
    push::<DeviceAuthorizationRequest>(&mut output, &cfg);
    push::<DeviceAuthorizationResponse>(&mut output, &cfg);
    push::<DeviceTokenRequest>(&mut output, &cfg);
    push::<DeviceTokenResponse>(&mut output, &cfg);

    push::<AdminLoginRequest>(&mut output, &cfg);
    push::<SysadminIdentity>(&mut output, &cfg);
    push::<LoginResponse>(&mut output, &cfg);
    push::<SysadminSummary>(&mut output, &cfg);
    push::<ListSysadminsResponse>(&mut output, &cfg);
    push::<WhoamiResponse>(&mut output, &cfg);
    push::<UserSummary>(&mut output, &cfg);
    push::<ListUsersResponse>(&mut output, &cfg);
    push::<UserDetail>(&mut output, &cfg);
    push::<ReleaseUserRequest>(&mut output, &cfg);
    push::<ReleaseUserResponse>(&mut output, &cfg);
    push::<InviteUserRequest>(&mut output, &cfg);
    push::<InviteAction>(&mut output, &cfg);
    push::<InviteUserResponse>(&mut output, &cfg);
    push::<SessionSummary>(&mut output, &cfg);
    push::<ListSessionsResponse>(&mut output, &cfg);
    push::<DeviceSessionSummary>(&mut output, &cfg);
    push::<ListDeviceSessionsResponse>(&mut output, &cfg);
    push::<OrgSummary>(&mut output, &cfg);
    push::<ListOrgsResponse>(&mut output, &cfg);
    push::<OrgDetail>(&mut output, &cfg);
    push::<CreateOrgRequest>(&mut output, &cfg);
    push::<UpdateOrgRequest>(&mut output, &cfg);
    push::<OrgMember>(&mut output, &cfg);
    push::<ListMembersResponse>(&mut output, &cfg);
    push::<AddMemberRequest>(&mut output, &cfg);
    push::<SetRoleRequest>(&mut output, &cfg);
    push::<TransferOwnershipRequest>(&mut output, &cfg);
    push::<OrgInvite>(&mut output, &cfg);
    push::<ListOrgInvitesResponse>(&mut output, &cfg);
    push::<CreateOrgInviteRequest>(&mut output, &cfg);
    push::<CreateOrgInviteResponse>(&mut output, &cfg);
    push::<SettingsResponse>(&mut output, &cfg);
    push::<WaitlistSettingsRequest>(&mut output, &cfg);
    push::<NamespaceStatusResponse>(&mut output, &cfg);

    output
}

/// Write the complete TypeScript declaration file to a path.
pub fn write_typescript_declarations(path: impl AsRef<Path>) -> io::Result<()> {
    fs::write(path, typescript_declarations())
}

/// Format a complete TypeScript declaration file.
pub fn format_typescript_declarations(input: &str, path: impl AsRef<Path>) -> io::Result<String> {
    let fmt_cfg = ConfigurationBuilder::new().deno().build();
    let path = path.as_ref();
    let options = FormatTextOptions {
        config: &fmt_cfg,
        path,
        text: input.to_owned(),
        extension: None,
        external_formatter: None,
    };
    format_text(options)
        .map_err(|err| io::Error::new(io::ErrorKind::InvalidData, err.to_string()))
        .map(|formatted| formatted.unwrap_or_else(|| input.to_owned()))
}

/// Append one exported declaration to the generated output.
fn push<T>(output: &mut String, cfg: &Config)
where
    T: TS + 'static,
{
    output.push_str("export ");
    output.push_str(T::decl(cfg).as_str());
    output.push_str("\n\n");
}

#[cfg(test)]
mod tests {
    //! Tests for generated TypeScript declarations.

    use std::{env, fs, path::PathBuf};

    use super::{
        TYPESCRIPT_DECLARATION_HEADER, TYPESCRIPT_DECLARATION_RELATIVE_PATH,
        typescript_declaration_body, typescript_declarations, write_typescript_declarations,
    };

    /// Resolve the generated declaration file from the crate directory.
    fn generated_path() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join(TYPESCRIPT_DECLARATION_RELATIVE_PATH)
    }

    /// Proves generated declarations include representative shared DTOs.
    #[test]
    fn declarations_include_representative_shared_types() {
        let declarations = typescript_declarations();

        assert!(declarations.contains("export type UserInfo"));
        assert!(declarations.contains("export type DeviceSessionInfo"));
        assert!(declarations.contains("export type ListDeviceSessionsResponse"));
        assert!(!declarations.contains("PlayerSession"));
    }

    /// Proves declaration bodies can be embedded in product-owned generated files.
    #[test]
    fn declaration_body_omits_file_header() {
        let declarations = typescript_declaration_body();

        assert!(declarations.contains("export type UserInfo"));
        assert!(!declarations.starts_with(TYPESCRIPT_DECLARATION_HEADER));
    }

    /// Regenerates the checked-in declaration file when run explicitly.
    #[test]
    #[ignore = "regenerates checked-in TypeScript declarations"]
    fn export_typescript_declarations() {
        write_typescript_declarations(generated_path()).expect("write generated declarations");
    }

    /// Proves the checked-in `@ankh/types` declarations are fresh.
    #[test]
    fn generated_typescript_declarations_are_current() {
        let expected = typescript_declarations();
        let current =
            fs::read_to_string(generated_path()).expect("generated declarations are readable");

        assert_eq!(current, expected);
    }
}
