// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-types
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ankh-cli, ankh-db, ankh-testdata, ankh-web

//! Shared API payload and identifier types for Ankh services.

use std::{
    fmt::{Debug, Display},
    hash::Hash,
    path::Path,
    str::FromStr,
};

use chrono::{DateTime, Utc};
use serde_core::{de::Deserialize, ser::Serialize};
use ts_rs::TS;
use uuid::Uuid;

/// Response body for accepting an organization invite.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AcceptOrgInviteResponse {
    /// Organization joined by accepting the invite.
    pub org: OrgInfo,
}

impl TS for AcceptOrgInviteResponse {
    type OptionInnerType = AcceptOrgInviteResponse;
    type WithoutGenerics = AcceptOrgInviteResponse;
    const IS_ENUM: bool = false;
}

/// Response body for the current auth identity endpoint.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AuthMeResponse {
    /// Current user if a web session is authenticated.
    pub user: Option<UserInfo>,
}

impl TS for AuthMeResponse {
    type OptionInnerType = AuthMeResponse;
    type WithoutGenerics = AuthMeResponse;
    const IS_ENUM: bool = false;
}

/// Authentication result for JSON auth endpoints.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AuthSuccess {
    /// Authenticated user info.
    pub user: UserInfo,
}

impl TS for AuthSuccess {
    type OptionInnerType = AuthSuccess;
    type WithoutGenerics = AuthSuccess;
    const IS_ENUM: bool = false;
}

/// Response body for minting a device session from an authenticated web
/// session.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct CreateDeviceSessionResponse {
    /// Raw bearer token returned once.
    pub token: String,
    /// Device label associated with the session.
    pub device_name: String,
    /// When the token expires.
    pub expires_at: String,
}

impl TS for CreateDeviceSessionResponse {
    type OptionInnerType = CreateDeviceSessionResponse;
    type WithoutGenerics = CreateDeviceSessionResponse;
    const IS_ENUM: bool = false;
}

/// Request to create a new organization.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct CreateOrgInput {
    /// Organization name.
    pub name: String,
    /// Optional display name.
    pub display_name: Option<String>,
}

impl TS for CreateOrgInput {
    type OptionInnerType = CreateOrgInput;
    type WithoutGenerics = CreateOrgInput;
    const IS_ENUM: bool = false;
}

/// Unique identifier for a device authorization grant.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct DeviceAuthGrantId(pub Uuid);

impl TS for DeviceAuthGrantId {
    type OptionInnerType = DeviceAuthGrantId;
    type WithoutGenerics = DeviceAuthGrantId;
    const IS_ENUM: bool = false;
}

/// Query parameters for the browser device authorization flow.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct DeviceAuthorizationRequest {
    /// PKCE S256 code challenge.
    pub code_challenge: String,
    /// Loopback redirect port.
    pub redirect_port: u16,
    /// Caller-provided state echoed back to the loopback callback.
    pub state: String,
    /// Human-readable device name.
    pub device_name: String,
    /// Platform identifier supplied by the device client.
    pub platform: DevicePlatform,
}

impl TS for DeviceAuthorizationRequest {
    type OptionInnerType = DeviceAuthorizationRequest;
    type WithoutGenerics = DeviceAuthorizationRequest;
    const IS_ENUM: bool = false;
}

/// Device authorization grant details returned internally by services.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct DeviceAuthorizationResponse {
    /// Raw one-time authorization code.
    pub code: String,
    /// Loopback callback URL.
    pub callback_url: String,
    /// When the grant expires.
    pub expires_at: DateTime<Utc>,
}

impl TS for DeviceAuthorizationResponse {
    type OptionInnerType = DeviceAuthorizationResponse;
    type WithoutGenerics = DeviceAuthorizationResponse;
    const IS_ENUM: bool = false;
}

/// Platform identifier for generic device sessions.
#[derive(Clone, Debug, Deserialize<'de>, Display, Eq, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub enum DevicePlatform {
    /// macOS native device.
    Macos,
    /// Windows native device.
    Windows,
    /// Linux native device.
    Linux,
    /// Browser or web runtime.
    Web,
    /// A platform not known to this version of Ankh.
    Other(String),
}

impl DevicePlatform {
    /// Return the stable database value for this platform.
    #[must_use]
    pub fn as_str(&self) -> &str;

    /// Parse a platform from a database string, preserving unknown values.
    #[must_use]
    pub fn parse_db(value: &str) -> Self;
}

impl TS for DevicePlatform {
    type OptionInnerType = DevicePlatform;
    type WithoutGenerics = DevicePlatform;
    const IS_ENUM: bool = true;
}

/// Unique identifier for a device session.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct DeviceSessionId(pub Uuid);

impl TS for DeviceSessionId {
    type OptionInnerType = DeviceSessionId;
    type WithoutGenerics = DeviceSessionId;
    const IS_ENUM: bool = false;
}

/// Device session info for UI display.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct DeviceSessionInfo {
    /// Session ID.
    pub id: String,
    /// Device name.
    pub device_name: String,
    /// Platform identifier.
    pub platform: DevicePlatform,
    /// Status: active, revoked, or expired.
    pub status: String,
    /// When the session was created.
    pub created_at: String,
    /// When the session was last used.
    pub last_used_at: String,
    /// When the session expires.
    pub expires_at: String,
}

impl TS for DeviceSessionInfo {
    type OptionInnerType = DeviceSessionInfo;
    type WithoutGenerics = DeviceSessionInfo;
    const IS_ENUM: bool = false;
}

/// Request body for exchanging a device authorization code.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct DeviceTokenRequest {
    /// Raw one-time authorization code.
    pub code: String,
    /// PKCE verifier corresponding to the authorization challenge.
    pub code_verifier: String,
}

impl TS for DeviceTokenRequest {
    type OptionInnerType = DeviceTokenRequest;
    type WithoutGenerics = DeviceTokenRequest;
    const IS_ENUM: bool = false;
}

/// Response body for a device authorization token exchange.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct DeviceTokenResponse {
    /// Raw bearer token returned once.
    pub token: String,
    /// Human-readable device name.
    pub device_name: String,
    /// Platform identifier stored for the session.
    pub platform: DevicePlatform,
    /// When the device session expires.
    pub expires_at: DateTime<Utc>,
}

impl TS for DeviceTokenResponse {
    type OptionInnerType = DeviceTokenResponse;
    type WithoutGenerics = DeviceTokenResponse;
    const IS_ENUM: bool = false;
}

/// Request body for password reset email creation.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ForgotPasswordRequest {
    /// Email address to send a reset link to.
    pub email: String,
}

impl TS for ForgotPasswordRequest {
    type OptionInnerType = ForgotPasswordRequest;
    type WithoutGenerics = ForgotPasswordRequest;
    const IS_ENUM: bool = false;
}

/// Unique identifier for an account invite.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct InviteId(pub Uuid);

impl TS for InviteId {
    type OptionInnerType = InviteId;
    type WithoutGenerics = InviteId;
    const IS_ENUM: bool = false;
}

/// Pending organization invite for UI display.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct InviteInfo {
    /// Invite ID.
    pub id: String,
    /// Email address invited.
    pub email: String,
    /// When the invite was created.
    pub created_at: String,
    /// When the invite expires.
    pub expires_at: String,
}

impl TS for InviteInfo {
    type OptionInnerType = InviteInfo;
    type WithoutGenerics = InviteInfo;
    const IS_ENUM: bool = false;
}

/// Request body for user login.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct LoginRequest {
    /// Email address or username.
    pub email: String,
    /// User password.
    pub password: String,
}

impl TS for LoginRequest {
    type OptionInnerType = LoginRequest;
    type WithoutGenerics = LoginRequest;
    const IS_ENUM: bool = false;
}

/// Organization member info for UI display.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct MemberInfo {
    /// User ID.
    pub user_id: String,
    /// Username.
    pub username: String,
    /// Email address.
    pub email: String,
    /// Role in the organization.
    pub role: String,
}

impl TS for MemberInfo {
    type OptionInnerType = MemberInfo;
    type WithoutGenerics = MemberInfo;
    const IS_ENUM: bool = false;
}

/// Unique identifier for a namespace owned by a user or org.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct NamespaceId(pub Uuid);

impl TS for NamespaceId {
    type OptionInnerType = NamespaceId;
    type WithoutGenerics = NamespaceId;
    const IS_ENUM: bool = false;
}

/// The kind of entity that owns a namespace.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[serde(rename_all = "snake_case")]
pub enum NamespaceKind {
    /// Namespace belongs to a user.
    User,
    /// Namespace belongs to an organization.
    Org,
}

impl NamespaceKind {
    /// Return the stable database storage value for this namespace kind.
    #[must_use]
    pub fn as_str(self) -> &'static str;

    /// Parse a namespace kind from its database representation.
    #[must_use]
    pub fn parse_db(s: &str) -> Option<Self>;
}

impl TS for NamespaceKind {
    type OptionInnerType = NamespaceKind;
    type WithoutGenerics = NamespaceKind;
    const IS_ENUM: bool = true;
}

/// Unique identifier for an organization.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct OrgId(pub Uuid);

impl TS for OrgId {
    type OptionInnerType = OrgId;
    type WithoutGenerics = OrgId;
    const IS_ENUM: bool = false;
}

/// Organization summary for UI display.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct OrgInfo {
    /// Organization ID, or namespace ID for personal organizations.
    pub id: String,
    /// Organization name.
    pub name: String,
    /// Optional display name.
    pub display_name: Option<String>,
    /// User's role in this organization.
    pub role: String,
    /// Whether this is a personal organization.
    pub is_personal: bool,
}

impl TS for OrgInfo {
    type OptionInnerType = OrgInfo;
    type WithoutGenerics = OrgInfo;
    const IS_ENUM: bool = false;
}

/// Organization invite details for acceptance flows.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct OrgInviteDetails {
    /// Organization name.
    pub org_name: String,
    /// Organization display name.
    pub org_display_name: Option<String>,
    /// Email the invite was sent to.
    pub invite_email: String,
}

impl TS for OrgInviteDetails {
    type OptionInnerType = OrgInviteDetails;
    type WithoutGenerics = OrgInviteDetails;
    const IS_ENUM: bool = false;
}

/// Unique identifier for an organization invite.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct OrgInviteId(pub Uuid);

impl TS for OrgInviteId {
    type OptionInnerType = OrgInviteId;
    type WithoutGenerics = OrgInviteId;
    const IS_ENUM: bool = false;
}

/// Current user's membership info in an organization.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct OrgMemberInfo {
    /// User ID.
    pub user_id: String,
    /// Username.
    pub username: String,
    /// Role in the organization.
    pub role: String,
}

impl TS for OrgMemberInfo {
    type OptionInnerType = OrgMemberInfo;
    type WithoutGenerics = OrgMemberInfo;
    const IS_ENUM: bool = false;
}

/// Role within an organization.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[serde(rename_all = "snake_case")]
pub enum OrgRole {
    /// Organization owner.
    Owner,
    /// Organization admin.
    Admin,
    /// Organization member.
    Member,
}

impl OrgRole {
    /// Return the stable database storage value for this role.
    #[must_use]
    pub fn as_str(self) -> &'static str;

    /// Return whether this role can change a target member's role.
    #[must_use]
    pub fn can_change_role(self, _target: Self) -> bool;

    /// Return whether this role can invite new members.
    #[must_use]
    pub fn can_invite(self) -> bool;

    /// Return whether this role can remove a target role.
    #[must_use]
    pub fn can_remove(self, target: Self) -> bool;

    /// Parse an org role from its database representation.
    #[must_use]
    pub fn parse_db(s: &str) -> Option<Self>;
}

impl TS for OrgRole {
    type OptionInnerType = OrgRole;
    type WithoutGenerics = OrgRole;
    const IS_ENUM: bool = true;
}

/// Request body for completing a password reset.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct PasswordResetRequest {
    /// Raw password reset token.
    pub token: String,
    /// New password.
    pub password: String,
}

impl TS for PasswordResetRequest {
    type OptionInnerType = PasswordResetRequest;
    type WithoutGenerics = PasswordResetRequest;
    const IS_ENUM: bool = false;
}

/// Request body for resending email verification.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ResendVerificationRequest {
    /// Email address to send a verification link to.
    pub email: String,
}

impl TS for ResendVerificationRequest {
    type OptionInnerType = ResendVerificationRequest;
    type WithoutGenerics = ResendVerificationRequest;
    const IS_ENUM: bool = false;
}

/// Unique identifier for a browser web session.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct SessionId(pub Uuid);

impl TS for SessionId {
    type OptionInnerType = SessionId;
    type WithoutGenerics = SessionId;
    const IS_ENUM: bool = false;
}

/// Request body for account signup.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct SignupRequest {
    /// Requested username.
    pub username: String,
    /// User email address.
    pub email: String,
    /// User password.
    pub password: String,
    /// Optional account invite token.
    pub invite_token: Option<String>,
    /// Optional organization invite token.
    pub org_invite_token: Option<String>,
}

impl TS for SignupRequest {
    type OptionInnerType = SignupRequest;
    type WithoutGenerics = SignupRequest;
    const IS_ENUM: bool = false;
}

/// Unique identifier for a sysadmin account.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct SysadminId(pub Uuid);

impl TS for SysadminId {
    type OptionInnerType = SysadminId;
    type WithoutGenerics = SysadminId;
    const IS_ENUM: bool = false;
}

/// Unique identifier for a sysadmin bearer token.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct SysadminTokenId(pub Uuid);

impl TS for SysadminTokenId {
    type OptionInnerType = SysadminTokenId;
    type WithoutGenerics = SysadminTokenId;
    const IS_ENUM: bool = false;
}

/// Unique identifier for a one-time identity token.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct TokenId(pub Uuid);

impl TS for TokenId {
    type OptionInnerType = TokenId;
    type WithoutGenerics = TokenId;
    const IS_ENUM: bool = false;
}

/// Unique identifier for a user.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Display, Eq, FromStr, Hash, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[ts(type = "string")]
pub struct UserId(pub Uuid);

impl TS for UserId {
    type OptionInnerType = UserId;
    type WithoutGenerics = UserId;
    const IS_ENUM: bool = false;
}

/// Lightweight user info returned from auth endpoints.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct UserInfo {
    /// User's unique username.
    pub username: String,
    /// User email address.
    pub email: String,
    /// Whether the email has been verified.
    pub email_verified: bool,
    /// Whether the account is currently waitlisted.
    pub waitlisted: bool,
}

impl TS for UserInfo {
    type OptionInnerType = UserInfo;
    type WithoutGenerics = UserInfo;
    const IS_ENUM: bool = false;
}

/// Request body for password reset token validation.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ValidateResetTokenRequest {
    /// Raw password reset token.
    pub token: String,
}

impl TS for ValidateResetTokenRequest {
    type OptionInnerType = ValidateResetTokenRequest;
    type WithoutGenerics = ValidateResetTokenRequest;
    const IS_ENUM: bool = false;
}

/// Response body for password reset token validation.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ValidateResetTokenResponse {
    /// Email address associated with the reset token.
    pub email: String,
}

impl TS for ValidateResetTokenResponse {
    type OptionInnerType = ValidateResetTokenResponse;
    type WithoutGenerics = ValidateResetTokenResponse;
    const IS_ENUM: bool = false;
}

/// Request body for email verification.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct VerificationRequest {
    /// Raw verification token.
    pub token: String,
}

impl TS for VerificationRequest {
    type OptionInnerType = VerificationRequest;
    type WithoutGenerics = VerificationRequest;
    const IS_ENUM: bool = false;
}

/// Response body for waitlist status.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct WaitlistStatusResponse {
    /// Whether waitlist mode is currently enabled.
    pub waitlist_enabled: bool,
}

impl TS for WaitlistStatusResponse {
    type OptionInnerType = WaitlistStatusResponse;
    type WithoutGenerics = WaitlistStatusResponse;
    const IS_ENUM: bool = false;
}

pub mod admin {
    //! Shared admin API request and response payloads.

    /// Request body for adding a member.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct AddMemberRequest {
        /// User ID to add.
        pub user_id: String,
        /// Role for the new member.
        #[serde(default = "default_member_role")]
        pub role: String,
    }

    impl TS for AddMemberRequest {
        type OptionInnerType = AddMemberRequest;
        type WithoutGenerics = AddMemberRequest;
        const IS_ENUM: bool = false;
    }

    /// Request body for sysadmin login.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct AdminLoginRequest {
        /// Sysadmin email address.
        pub email: String,
        /// Sysadmin password.
        pub password: String,
    }

    impl TS for AdminLoginRequest {
        type OptionInnerType = AdminLoginRequest;
        type WithoutGenerics = AdminLoginRequest;
        const IS_ENUM: bool = false;
    }

    /// Request body for creating an org invite.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct CreateOrgInviteRequest {
        /// Email to invite.
        pub email: String,
    }

    impl TS for CreateOrgInviteRequest {
        type OptionInnerType = CreateOrgInviteRequest;
        type WithoutGenerics = CreateOrgInviteRequest;
        const IS_ENUM: bool = false;
    }

    /// Response body for creating an org invite.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct CreateOrgInviteResponse {
        /// Invite ID.
        pub id: String,
        /// Invited email.
        pub email: String,
        /// Raw token returned only on creation.
        pub token: String,
    }

    impl TS for CreateOrgInviteResponse {
        type OptionInnerType = CreateOrgInviteResponse;
        type WithoutGenerics = CreateOrgInviteResponse;
        const IS_ENUM: bool = false;
    }

    /// Request body for creating an org.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct CreateOrgRequest {
        /// Organization name.
        pub name: String,
        /// Optional display name.
        pub display_name: Option<String>,
        /// User ID who will be the owner.
        pub owner_id: String,
    }

    impl TS for CreateOrgRequest {
        type OptionInnerType = CreateOrgRequest;
        type WithoutGenerics = CreateOrgRequest;
        const IS_ENUM: bool = false;
    }

    /// Device session summary in admin list responses.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct DeviceSessionSummary {
        /// Session ID.
        pub id: String,
        /// User ID that owns this session.
        pub user_id: String,
        /// User email.
        pub user_email: String,
        /// Device name for the session.
        pub device_name: String,
        /// Platform identifier.
        pub platform: String,
        /// Computed status based on revoked_at and expires_at.
        pub status: String,
        /// When the session was created.
        pub created_at: DateTime<Utc>,
        /// When the session was last used.
        pub last_used_at: DateTime<Utc>,
        /// When the session expires.
        pub expires_at: DateTime<Utc>,
        /// When the session was revoked, if ever.
        pub revoked_at: Option<DateTime<Utc>>,
    }

    impl TS for DeviceSessionSummary {
        type OptionInnerType = DeviceSessionSummary;
        type WithoutGenerics = DeviceSessionSummary;
        const IS_ENUM: bool = false;
    }

    /// Action taken by the invite endpoint.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
#[serde(rename_all = "snake_case")]
    pub enum InviteAction {
        /// Invite email sent.
        Invited,
        /// Existing waitlisted user released.
        Released,
        /// User already active.
        AlreadyActive,
    }

    impl TS for InviteAction {
        type OptionInnerType = InviteAction;
        type WithoutGenerics = InviteAction;
        const IS_ENUM: bool = true;
    }

    /// Request body for inviting a user.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct InviteUserRequest {
        /// User email to invite.
        pub email: String,
    }

    impl TS for InviteUserRequest {
        type OptionInnerType = InviteUserRequest;
        type WithoutGenerics = InviteUserRequest;
        const IS_ENUM: bool = false;
    }

    /// Response body for inviting a user.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct InviteUserResponse {
        /// User email address.
        pub email: String,
        /// Action taken for the invite request.
        pub action: InviteAction,
    }

    impl TS for InviteUserResponse {
        type OptionInnerType = InviteUserResponse;
        type WithoutGenerics = InviteUserResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for listing device sessions.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ListDeviceSessionsResponse {
        /// List of device sessions.
        pub sessions: Vec<DeviceSessionSummary>,
        /// Cursor for fetching the next page, if more results exist.
        pub next_cursor: Option<String>,
    }

    impl TS for ListDeviceSessionsResponse {
        type OptionInnerType = ListDeviceSessionsResponse;
        type WithoutGenerics = ListDeviceSessionsResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for listing org members.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ListMembersResponse {
        /// List of members.
        pub members: Vec<OrgMember>,
    }

    impl TS for ListMembersResponse {
        type OptionInnerType = ListMembersResponse;
        type WithoutGenerics = ListMembersResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for listing org invites.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ListOrgInvitesResponse {
        /// List of invites.
        pub invites: Vec<OrgInvite>,
    }

    impl TS for ListOrgInvitesResponse {
        type OptionInnerType = ListOrgInvitesResponse;
        type WithoutGenerics = ListOrgInvitesResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for listing orgs.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ListOrgsResponse {
        /// List of organizations.
        pub orgs: Vec<OrgSummary>,
        /// Cursor for fetching the next page.
        pub next_cursor: Option<String>,
    }

    impl TS for ListOrgsResponse {
        type OptionInnerType = ListOrgsResponse;
        type WithoutGenerics = ListOrgsResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for listing sessions.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ListSessionsResponse {
        /// List of sessions.
        pub sessions: Vec<SessionSummary>,
        /// Cursor for fetching the next page, if more results exist.
        pub next_cursor: Option<String>,
    }

    impl TS for ListSessionsResponse {
        type OptionInnerType = ListSessionsResponse;
        type WithoutGenerics = ListSessionsResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for listing sysadmins.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ListSysadminsResponse {
        /// List of sysadmins.
        pub sysadmins: Vec<SysadminSummary>,
        /// Cursor for fetching the next page, if more results exist.
        pub next_cursor: Option<String>,
    }

    impl TS for ListSysadminsResponse {
        type OptionInnerType = ListSysadminsResponse;
        type WithoutGenerics = ListSysadminsResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for listing users.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ListUsersResponse {
        /// List of users.
        pub users: Vec<UserSummary>,
        /// Cursor for fetching the next page, if more results exist.
        pub next_cursor: Option<String>,
    }

    impl TS for ListUsersResponse {
        type OptionInnerType = ListUsersResponse;
        type WithoutGenerics = ListUsersResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for successful admin login.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct LoginResponse {
        /// Bearer token to use for authenticated requests.
        pub token: String,
        /// Token expiration timestamp.
        pub expires_at: DateTime<Utc>,
        /// Authenticated sysadmin identity.
        pub sysadmin: SysadminIdentity,
    }

    impl TS for LoginResponse {
        type OptionInnerType = LoginResponse;
        type WithoutGenerics = LoginResponse;
        const IS_ENUM: bool = false;
    }

    /// Response body for namespace status changes.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct NamespaceStatusResponse {
        /// Namespace ID.
        pub id: String,
        /// Namespace status.
        pub status: String,
        /// Namespace generation after the mutation.
        #[serde(rename = "gen")]
        #[ts(rename = "gen")]
        pub r#gen: i64,
    }

    impl TS for NamespaceStatusResponse {
        type OptionInnerType = NamespaceStatusResponse;
        type WithoutGenerics = NamespaceStatusResponse;
        const IS_ENUM: bool = false;
    }

    /// Organization detail in get responses.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct OrgDetail {
        /// Organization ID.
        pub id: String,
        /// Organization name.
        pub name: String,
        /// Display name.
        pub display_name: Option<String>,
        /// User who created the org, if the creator still exists.
        pub created_by: Option<String>,
        /// Namespace ID owned by the org.
        pub namespace_id: String,
        /// Namespace status.
        pub namespace_status: String,
        /// Namespace generation.
        pub namespace_gen: i64,
        /// When the org was created.
        pub created_at: DateTime<Utc>,
        /// When the org was last updated.
        pub updated_at: DateTime<Utc>,
    }

    impl TS for OrgDetail {
        type OptionInnerType = OrgDetail;
        type WithoutGenerics = OrgDetail;
        const IS_ENUM: bool = false;
    }

    /// Organization invite in response.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct OrgInvite {
        /// Invite ID.
        pub id: String,
        /// Invited email.
        pub email: String,
        /// When the invite was created.
        pub created_at: DateTime<Utc>,
        /// When the invite expires.
        pub expires_at: DateTime<Utc>,
        /// When the invite was accepted, if ever.
        pub accepted_at: Option<DateTime<Utc>>,
        /// When the invite was revoked, if ever.
        pub revoked_at: Option<DateTime<Utc>>,
    }

    impl TS for OrgInvite {
        type OptionInnerType = OrgInvite;
        type WithoutGenerics = OrgInvite;
        const IS_ENUM: bool = false;
    }

    /// Organization member in response.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct OrgMember {
        /// User ID.
        pub user_id: String,
        /// Username.
        pub username: String,
        /// Email address.
        pub email: String,
        /// Role in the organization.
        pub role: String,
        /// When the member was added.
        pub created_at: DateTime<Utc>,
    }

    impl TS for OrgMember {
        type OptionInnerType = OrgMember;
        type WithoutGenerics = OrgMember;
        const IS_ENUM: bool = false;
    }

    /// Organization summary in list responses.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct OrgSummary {
        /// Organization ID.
        pub id: String,
        /// Organization name.
        pub name: String,
        /// Display name.
        pub display_name: Option<String>,
        /// When the org was created.
        pub created_at: DateTime<Utc>,
    }

    impl TS for OrgSummary {
        type OptionInnerType = OrgSummary;
        type WithoutGenerics = OrgSummary;
        const IS_ENUM: bool = false;
    }

    /// Request body for releasing a waitlisted user.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ReleaseUserRequest {
        /// User ID to release.
        pub id: Option<String>,
        /// User email to release.
        pub email: Option<String>,
    }

    impl TS for ReleaseUserRequest {
        type OptionInnerType = ReleaseUserRequest;
        type WithoutGenerics = ReleaseUserRequest;
        const IS_ENUM: bool = false;
    }

    /// Response body for releasing a waitlisted user.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct ReleaseUserResponse {
        /// User email address.
        pub email: String,
    }

    impl TS for ReleaseUserResponse {
        type OptionInnerType = ReleaseUserResponse;
        type WithoutGenerics = ReleaseUserResponse;
        const IS_ENUM: bool = false;
    }

    /// Session summary in list responses.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct SessionSummary {
        /// Session ID.
        pub id: String,
        /// User ID that owns this session.
        pub user_id: String,
        /// User email.
        pub user_email: String,
        /// Computed status based on revoked_at and expires_at.
        pub status: String,
        /// When the session was created.
        pub created_at: DateTime<Utc>,
        /// When the session was last used.
        pub last_seen_at: DateTime<Utc>,
        /// When the session expires.
        pub expires_at: DateTime<Utc>,
        /// When the session was revoked, if ever.
        pub revoked_at: Option<DateTime<Utc>>,
    }

    impl TS for SessionSummary {
        type OptionInnerType = SessionSummary;
        type WithoutGenerics = SessionSummary;
        const IS_ENUM: bool = false;
    }

    /// Request body for setting a member's role.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct SetRoleRequest {
        /// New role.
        pub role: String,
    }

    impl TS for SetRoleRequest {
        type OptionInnerType = SetRoleRequest;
        type WithoutGenerics = SetRoleRequest;
        const IS_ENUM: bool = false;
    }

    /// Response body for settings queries.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct SettingsResponse {
        /// Whether waitlist mode is enabled.
        pub waitlist_enabled: bool,
    }

    impl TS for SettingsResponse {
        type OptionInnerType = SettingsResponse;
        type WithoutGenerics = SettingsResponse;
        const IS_ENUM: bool = false;
    }

    /// Sysadmin identity returned by authentication flows.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct SysadminIdentity {
        /// Sysadmin ID.
        pub id: String,
        /// Sysadmin email address.
        pub email: String,
    }

    impl TS for SysadminIdentity {
        type OptionInnerType = SysadminIdentity;
        type WithoutGenerics = SysadminIdentity;
        const IS_ENUM: bool = false;
    }

    /// Sysadmin summary in list responses.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct SysadminSummary {
        /// Sysadmin ID.
        pub id: String,
        /// Sysadmin email address.
        pub email: String,
        /// When the sysadmin was created.
        pub created_at: DateTime<Utc>,
        /// When the sysadmin last logged in, if ever.
        pub last_login_at: Option<DateTime<Utc>>,
    }

    impl TS for SysadminSummary {
        type OptionInnerType = SysadminSummary;
        type WithoutGenerics = SysadminSummary;
        const IS_ENUM: bool = false;
    }

    /// Request body for transferring ownership.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct TransferOwnershipRequest {
        /// User ID of new owner.
        pub new_owner_id: String,
    }

    impl TS for TransferOwnershipRequest {
        type OptionInnerType = TransferOwnershipRequest;
        type WithoutGenerics = TransferOwnershipRequest;
        const IS_ENUM: bool = false;
    }

    /// Request body for updating an org.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct UpdateOrgRequest {
        /// New display name.
        pub display_name: Option<String>,
    }

    impl TS for UpdateOrgRequest {
        type OptionInnerType = UpdateOrgRequest;
        type WithoutGenerics = UpdateOrgRequest;
        const IS_ENUM: bool = false;
    }

    /// User detail in get responses.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct UserDetail {
        /// User ID.
        pub id: String,
        /// User's unique username.
        pub username: String,
        /// User email address.
        pub email: String,
        /// When the user was created.
        pub created_at: DateTime<Utc>,
        /// When the email was verified, if ever.
        pub verified_at: Option<DateTime<Utc>>,
        /// Most recent session activity, if any sessions exist.
        pub last_session_at: Option<DateTime<Utc>>,
    }

    impl TS for UserDetail {
        type OptionInnerType = UserDetail;
        type WithoutGenerics = UserDetail;
        const IS_ENUM: bool = false;
    }

    /// User summary in list responses.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct UserSummary {
        /// User ID.
        pub id: String,
        /// User's unique username.
        pub username: String,
        /// User email address.
        pub email: String,
        /// When the user was created.
        pub created_at: DateTime<Utc>,
        /// When the email was verified, if ever.
        pub verified_at: Option<DateTime<Utc>>,
    }

    impl TS for UserSummary {
        type OptionInnerType = UserSummary;
        type WithoutGenerics = UserSummary;
        const IS_ENUM: bool = false;
    }

    /// Request body for updating waitlist settings.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct WaitlistSettingsRequest {
        /// Desired waitlist enablement.
        pub enabled: bool,
    }

    impl TS for WaitlistSettingsRequest {
        type OptionInnerType = WaitlistSettingsRequest;
        type WithoutGenerics = WaitlistSettingsRequest;
        const IS_ENUM: bool = false;
    }

    /// Response body for the authenticated sysadmin identity.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct WhoamiResponse {
        /// Authenticated sysadmin info.
        pub sysadmin: SysadminSummary,
    }

    impl TS for WhoamiResponse {
        type OptionInnerType = WhoamiResponse;
        type WithoutGenerics = WhoamiResponse;
        const IS_ENUM: bool = false;
    }
}

pub mod ts {
    //! TypeScript declaration generation for shared Ankh DTOs.

    /// Header used for generated TypeScript declaration files.
    pub const TYPESCRIPT_DECLARATION_HEADER: &str =
        "// Generated by ankh-types. Do not edit by hand.\n\n";

    /// Relative path to the generated declaration file consumed by `@ankh/types`.
    pub const TYPESCRIPT_DECLARATION_RELATIVE_PATH: &str =
        "frontend/packages/types/src/generated.d.ts";

    /// Format a complete TypeScript declaration file.
    pub fn format_typescript_declarations(
        input: &str,
        path: impl AsRef<Path>,
    ) -> std::io::Result<String>;

    /// Generate the Ankh-owned declaration body without the file header.
    #[must_use]
    pub fn typescript_declaration_body() -> String;

    /// Generate the complete TypeScript declaration file.
    #[must_use]
    pub fn typescript_declarations() -> String;

    /// Write the complete TypeScript declaration file to a path.
    pub fn write_typescript_declarations(path: impl AsRef<Path>) -> std::io::Result<()>;
}
