// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-xtask
// Publish: no
// Binaries: ankh-xtask
// Workspace dependencies: ankh-db
// Workspace dependents: none

//! Shared developer-task building blocks for Ankh and leaf workspaces.

use std::{
    error::Error,
    fmt::Debug,
    path::{Path, PathBuf},
    process::{Command, ExitStatus},
    time::Duration,
};

pub mod admin {
    //! Dev admin CLI helpers.
    //! Shared helpers for dev admin CLI auto-authentication.

    /// Dev admin login settings.
    #[derive(Clone, Debug)]
    pub struct AdminLogin {
        /// CLI config file that stores the dev profile credentials.
        pub config_path: PathBuf,
        /// CLI profile name.
        pub profile: String,
        /// Admin API base URL.
        pub base_url: String,
        /// Dev sysadmin email address.
        pub email: String,
        /// Dev sysadmin password.
        pub password: String,
    }

    impl AdminLogin {
        /// Build a new admin login settings value.
        #[must_use]
        pub fn new(
            config_path: impl Into<PathBuf>,
            profile: impl Into<String>,
            base_url: impl Into<String>,
            email: impl Into<String>,
            password: impl Into<String>,
        ) -> Self;
    }

    /// Cargo-run target for a leaf admin CLI binary.
    #[derive(Clone, Debug)]
    pub struct CargoAdminCli {
        /// Workspace where `cargo run` should execute.
        pub workspace_root: PathBuf,
        /// Package name containing the leaf CLI binary.
        pub package: String,
    }

    impl CargoAdminCli {
        /// Build a new Cargo admin CLI target.
        #[must_use]
        pub fn new(workspace_root: impl Into<PathBuf>, package: impl Into<String>) -> Self;
    }

    /// Build the standard `auth login` arguments for a dev admin profile.
    #[must_use]
    pub fn admin_login_args(login: &AdminLogin) -> Vec<String>;

    /// Authenticate the dev admin profile for a leaf CLI.
    pub fn ensure_admin_login(cli: &CargoAdminCli, login: &AdminLogin) -> XtaskResult;

    /// Run a leaf CLI package through Cargo with the supplied arguments.
    pub fn run_cli(cli: &CargoAdminCli, args: &[String]) -> XtaskResult;
}

pub mod command {
    //! Command execution helpers.
    //! Command execution and workspace helper APIs.

    /// Result type used by xtask helpers.
    pub type XtaskResult<T = ()> = Result<T, Box<dyn Error>>;

    /// Return true if `name` is available on `PATH`.
    #[must_use]
    pub fn binary_available(name: &str) -> bool;

    /// Convert a non-successful exit status into a friendly error message.
    pub fn ensure_success(status: ExitStatus, label: &str) -> XtaskResult;

    /// Execute `cargo` in `workspace_root` with optional passthrough arguments.
    pub fn exec_cargo(
        workspace_root: &Path,
        base_args: &[&str],
        passthrough: &[String],
    ) -> XtaskResult;

    /// Render command arguments for logging.
    #[must_use]
    pub fn format_args(base_args: &[&str], passthrough: &[String]) -> String;

    /// Ensure every binary in `names` is present on `PATH`.
    pub fn require_bins(names: &[&str]) -> XtaskResult;

    /// Drive an async action that returns an error from a synchronous xtask
    /// context.
    pub fn run_async_result<T, E>(future: impl Future<Output = Result<T, E>>) -> XtaskResult<T>
    where
        E: 'static + Error;

    /// Run rustfmt using `rustfmt-nightly.toml` when the workspace provides it.
    pub fn run_rustfmt(workspace_root: &Path) -> XtaskResult;

    /// Execute a prepared command, returning a friendly error for non-zero status.
    pub fn run_status(command: &mut Command, label: &str) -> XtaskResult;

    /// Resolve a workspace root from an xtask crate manifest directory.
    #[must_use]
    pub fn workspace_root_from_manifest(manifest_dir: &str) -> PathBuf;
}

pub mod frontend {
    //! Frontend package-manager helpers.
    //! Frontend package-manager helpers.

    /// Ensure a pnpm workspace has dependencies installed from its lockfile.
    pub fn ensure_pnpm_dependencies(frontend_root: &Path) -> XtaskResult;

    /// Run a pnpm command in `frontend_root`.
    pub fn run_pnpm(frontend_root: &Path, args: &[&str]) -> XtaskResult;

    /// Run a pnpm command only when dependencies and pnpm are available.
    pub fn run_pnpm_if_available(frontend_root: &Path, args: &[&str]) -> XtaskResult;

    /// Run a pnpm script after installing dependencies from the checked-in
    /// lockfile.
    pub fn run_pnpm_script_with_install(frontend_root: &Path, script: &str) -> XtaskResult;
}

pub mod postgres {
    //! Local Postgres lifecycle helpers.
    //! Local Postgres lifecycle helpers.

    /// Number of readiness polls performed before giving up on Postgres startup.
    pub const DEFAULT_READY_ATTEMPTS: u32 = 80;

    /// Delay between readiness polls.
    pub const DEFAULT_READY_BACKOFF: Duration = _;

    /// Hostname used for local Postgres connections.
    pub const LOCALHOST: &str = "localhost";

    /// Maintenance database used for readiness checks.
    pub const POSTGRES_DATABASE: &str = "postgres";

    /// Binaries required for local Postgres orchestration.
    pub const REQUIRED_BINS: &[&str] = _;

    /// User request for a local Postgres command.
    #[derive(Clone, Debug, Default)]
    pub struct DbRequest {
        /// Recreate the data directory from scratch.
        pub recreate: bool,
        /// Only report status without starting or stopping.
        pub status: bool,
        /// Stop the instance if it is running.
        pub stop: bool,
    }

    /// Shared Postgres lifecycle configuration.
    #[derive(Clone, Debug)]
    pub struct PostgresConfig<'a> {
        /// Hostname used for local connections.
        pub host: &'a str,
        /// Port to bind and inspect.
        pub port: u16,
        /// Maintenance database used by `pg_isready`.
        pub maintenance_database: &'a str,
        /// Workspace-local Postgres paths.
        pub paths: PostgresPaths,
        /// Databases created on a fresh data directory.
        pub bootstrap_databases: &'a [&'a str],
        /// Database seeded by `run_db` when seeding is requested.
        pub dev_database: &'a str,
        /// SQL used by `run_reset_db` to clear a database before bootstrapping.
        pub drop_tables_sql: &'a str,
    }

    impl<'a> PostgresConfig<'a> {
        /// Create a configuration with conventional localhost readiness settings.
        #[must_use]
        pub fn local(
            port: u16,
            paths: PostgresPaths,
            bootstrap_databases: &'a [&'a str],
            dev_database: &'a str,
            drop_tables_sql: &'a str,
        ) -> Self;
    }

    /// Paths owned by a workspace-local Postgres instance.
    #[derive(Clone, Debug)]
    pub struct PostgresPaths {
        /// Data directory.
        pub data_dir: PathBuf,
        /// Unix socket directory.
        pub socket_dir: PathBuf,
        /// Log file.
        pub log_file: PathBuf,
    }

    impl PostgresPaths {
        /// Build paths from a workspace root and relative path strings.
        #[must_use]
        pub fn from_root(
            workspace_root: &Path,
            data_dir: &str,
            socket_dir: &str,
            log_file: &str,
        ) -> Self;
    }

    /// Live status for the workspace Postgres instance.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub struct PostgresStatus {
        /// Port checked for readiness.
        pub port: u16,
        /// True when the workspace data directory reports a running server.
        pub running: bool,
        /// True when `pg_isready` succeeds on the configured port.
        pub healthy: bool,
        /// True when another server occupies the port while this data dir is
        /// stopped.
        pub conflict: bool,
    }

    impl PostgresStatus {
        /// Render the status label used by dev status commands.
        #[must_use]
        pub fn label(self) -> &'static str;
    }

    /// Controls whether startup reseeds databases.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum SeedMode {
        /// Always reseed after startup.
        Always,
        /// Only reseed when bootstrapping a fresh data directory.
        FreshOnly,
    }

    impl SeedMode {
        /// Return true when the selected mode should reseed after startup.
        #[must_use]
        pub fn should_seed(self, fresh: bool) -> bool;
    }

    /// Ensure the workspace Postgres instance is running without reseeding.
    pub fn ensure_db<Bootstrap, Seed>(
        config: &PostgresConfig<'_>,
        bootstrap: &Bootstrap,
        seed: &Seed,
    ) -> XtaskResult
    where
        Bootstrap: Fn(u16, &str) -> XtaskResult,
        Seed: Fn(u16, &str) -> XtaskResult;

    /// Report live status for the workspace Postgres instance.
    pub fn postgres_status(config: &PostgresConfig<'_>) -> XtaskResult<PostgresStatus>;

    /// Start, stop, recreate, or report a workspace-local Postgres instance.
    pub fn run_db<Bootstrap, Seed>(
        config: &PostgresConfig<'_>,
        request: &DbRequest,
        seed_mode: SeedMode,
        bootstrap: &Bootstrap,
        seed: &Seed,
    ) -> XtaskResult
    where
        Bootstrap: Fn(u16, &str) -> XtaskResult,
        Seed: Fn(u16, &str) -> XtaskResult;

    /// Open an interactive psql shell to a database.
    pub fn run_psql(config: &PostgresConfig<'_>, database: &str) -> XtaskResult;

    /// Reset a database by dropping tables, bootstrapping schemas, and seeding
    /// fixtures.
    pub fn run_reset_db<Bootstrap, Seed>(
        config: &PostgresConfig<'_>,
        database: &str,
        bootstrap: &Bootstrap,
        seed: &Seed,
    ) -> XtaskResult
    where
        Bootstrap: Fn(u16, &str) -> XtaskResult,
        Seed: Fn(u16, &str) -> XtaskResult;

    /// Stop the workspace Postgres instance if it is running.
    pub fn stop_if_running(config: &PostgresConfig<'_>) -> XtaskResult<bool>;
}

pub mod web {
    //! Simple webdev state-file helpers.
    //! Simple key/value state-file helpers for local webdev wrappers.

    /// Persisted key/value webdev state.
    #[derive(Clone, Debug, Default, Eq, PartialEq)]
    pub struct WebdevState {/* private fields */}

    impl WebdevState {
        /// Return the recorded base URL, if present.
        #[must_use]
        pub fn base_url(&self) -> Option<&str>;

        /// Read a state value.
        #[must_use]
        pub fn get(&self, key: &str) -> Option<&str>;

        /// Create an empty webdev state.
        #[must_use]
        pub fn new() -> Self;

        /// Parse state from `key=value` lines.
        pub fn parse(contents: &str) -> Result<Self, Box<dyn Error>>;

        /// Serialize the state as `key=value` lines.
        #[must_use]
        pub fn serialize(&self) -> String;

        /// Set a state value.
        pub fn set(&mut self, key: &str, value: impl Into<String>);
    }

    /// File-backed webdev state.
    #[derive(Clone, Debug)]
    pub struct WebdevStateFile {/* private fields */}

    impl WebdevStateFile {
        /// Load only the recorded base URL.
        pub fn base_url(&self) -> Result<Option<String>, Box<dyn Error>>;

        /// Load persisted state, returning `None` when no file exists.
        pub fn load(&self) -> Result<Option<WebdevState>, Box<dyn Error>>;

        /// Create a state-file handle.
        #[must_use]
        pub fn new(path: impl Into<PathBuf>) -> Self;

        /// Resolve the underlying state-file path.
        #[must_use]
        pub fn path(&self) -> &Path;

        /// Remove the state file if it exists.
        pub fn remove(&self) -> Result<(), Box<dyn Error>>;

        /// Write state to disk.
        pub fn write(&self, state: &WebdevState) -> Result<(), Box<dyn Error>>;
    }
}
