// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-constants
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ankh-cli (dev), ankh-db, ankh-testdata, ankh-web

//! Shared identity, session, device, mail, and admin constants.

use std::{fmt::Debug, time::Duration};

/// Admin endpoint defaults.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct AdminConfig {
    /// Default sysadmin token time-to-live.
    pub token_ttl: Duration,
    /// Total sysadmin login attempts allowed each minute.
    pub login_global_per_minute: u32,
    /// Default page size for admin list endpoints.
    pub list_default_limit: i64,
    /// Maximum page size accepted by admin list endpoints.
    pub list_max_limit: i64,
}

/// Auth endpoint rate-limit defaults.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct AuthRateLimits {
    /// Per-email login attempts allowed each minute.
    pub user_login_per_minute: u32,
    /// Total login attempts allowed each minute.
    pub user_login_global_per_minute: u32,
    /// Per-email signup attempts allowed each hour.
    pub signup_per_hour: u32,
    /// Total signup attempts allowed each hour.
    pub signup_global_per_hour: u32,
    /// Per-email password reset attempts allowed each hour.
    pub password_reset_per_hour: u32,
    /// Total password reset attempts allowed each hour.
    pub password_reset_global_per_hour: u32,
    /// Per-IP device authorization exchange attempts allowed each minute.
    pub device_auth_exchange_per_minute: u32,
}

/// Device authorization and session defaults grouped for service configuration.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct DeviceSessionConfig {
    /// Time-to-live for device authorization grants.
    pub grant_ttl: Duration,
    /// Maximum verification attempts allowed per authorization grant.
    pub grant_max_attempts: u32,
    /// Time-to-live for device bearer sessions.
    pub session_ttl: Duration,
    /// Maximum concurrent device sessions per user.
    pub session_limit: u32,
    /// Maximum length of a device label.
    pub device_name_max_len: usize,
}

/// Identity token defaults grouped for service configuration.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct IdentityTokenConfig {
    /// Time-to-live for email verification tokens.
    pub email_verification_ttl: Duration,
    /// Time-to-live for password reset tokens.
    pub password_reset_ttl: Duration,
    /// Cooldown between verification resend attempts.
    pub verification_resend_cooldown: Duration,
    /// Time-to-live for organization invite links.
    pub org_invite_ttl: Duration,
    /// Time-to-live for account invite links.
    pub user_invite_ttl: Duration,
}

/// Password policy defaults.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct PasswordPolicy {
    /// Minimum accepted password length.
    pub min_len: usize,
}

/// Session defaults grouped for service configuration.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct WebSessionConfig {
    /// Time-to-live for newly issued browser sessions.
    pub ttl: Duration,
    /// Idle interval after which a session touch updates `last_seen_at`.
    pub touch_stale_after: Duration,
}

/// Default page size for admin list endpoints.
pub const ADMIN_LIST_DEFAULT_LIMIT: i64 = 50;

/// Maximum page size accepted by admin list endpoints.
pub const ADMIN_LIST_MAX_LIMIT: i64 = 100;

/// Total sysadmin login attempts allowed each minute.
pub const ADMIN_LOGIN_GLOBAL_RATE_PER_MINUTE: u32 = 10;

/// Default time-to-live for newly issued browser sessions.
pub const DEFAULT_SESSION_TTL: Duration = _;

/// Default time-to-live for sysadmin tokens.
pub const DEFAULT_SYSADMIN_TOKEN_TTL: Duration = _;

/// Per-IP device authorization exchange attempts allowed each minute.
pub const DEVICE_AUTH_EXCHANGE_RATE_PER_MINUTE: u32 = 20;

/// Maximum verification attempts allowed per device authorization grant.
pub const DEVICE_AUTH_GRANT_MAX_ATTEMPTS: u32 = 5;

/// Time-to-live for device authorization grants.
pub const DEVICE_AUTH_GRANT_TTL: Duration = _;

/// Maximum length of a device session label.
pub const DEVICE_NAME_MAX_LEN: usize = 64;

/// Maximum number of concurrent device sessions per user.
pub const DEVICE_SESSION_LIMIT: u32 = 10;

/// Time-to-live for device sessions.
pub const DEVICE_SESSION_TTL: Duration = _;

/// Time-to-live for email verification tokens.
pub const EMAIL_VERIFICATION_TTL: Duration = _;

/// Minimum accepted password length.
pub const MIN_PASSWORD_LEN: usize = 8;

/// Time-to-live for organization invite links.
pub const ORG_INVITE_TTL: Duration = _;

/// Total password reset attempts allowed each hour.
pub const PASSWORD_RESET_GLOBAL_PER_HOUR: u32 = 100;

/// Per-email password reset attempts allowed each hour.
pub const PASSWORD_RESET_RATE_PER_HOUR: u32 = 10;

/// Time-to-live for password reset tokens.
pub const PASSWORD_RESET_TTL: Duration = _;

/// Idle interval after which a session touch updates its last-used timestamp.
pub const SESSION_TOUCH_STALE_AFTER: Duration = _;

/// Total signup attempts allowed each hour.
pub const SIGNUP_GLOBAL_PER_HOUR: u32 = 100;

/// Per-email signup attempts allowed each hour.
pub const SIGNUP_RATE_PER_HOUR: u32 = 10;

/// Time-to-live for account invite links created by admins.
pub const USER_INVITE_TTL: Duration = _;

/// Total login attempts allowed each minute.
pub const USER_LOGIN_GLOBAL_PER_MINUTE: u32 = 300;

/// Per-email login attempts allowed each minute.
pub const USER_LOGIN_RATE_PER_MINUTE: u32 = 20;

/// Cooldown between verification resend attempts.
pub const VERIFICATION_RESEND_COOLDOWN: Duration = _;
