// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-names
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ankh-db, ankh-web

//! Shared namespace name validation and reserved-name policy composition.

use std::fmt::Debug;

/// Product-specific extension to the shared namespace reservation policy.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct NamePolicy {/* private fields */}

impl NamePolicy {
    /// Return whether a namespace name is reserved by either shared or product
    /// policy.
    #[must_use]
    pub fn is_reserved_namespace_name(&self, name: &str) -> bool;

    /// Return product-specific reserved names.
    #[must_use]
    pub fn product_reserved(&self) -> &[String];

    /// Create a name policy with no product-specific reserved names.
    #[must_use]
    pub fn shared() -> Self;

    /// Validate a namespace name with this policy.
    pub fn validate_namespace_name(&self, name: &str) -> Result<(), &'static str>;

    /// Create a name policy with product-specific reserved names.
    #[must_use]
    pub fn with_product_reserved(names: impl IntoIterator<Item = impl Into<String>>) -> Self;
}

/// Return whether a name is reserved by the shared namespace policy.
///
/// Module-level convenience for the default (no product extension) policy; use
/// [`NamePolicy::is_reserved_namespace_name`] when a product adds reserved
/// names.
#[must_use]
pub fn is_reserved_namespace_name(name: &str) -> bool;

/// Normalizes a name for storage and comparison.
#[must_use]
pub fn normalize_name(name: &str) -> String;

/// Validates the shared format rules for namespace-like names.
pub fn validate_name_format(name: &str) -> Result<(), &'static str>;

/// Validates a namespace name with the shared reserved-word policy.
///
/// Module-level convenience for the default (no product extension) policy; use
/// [`NamePolicy::validate_namespace_name`] when a product adds reserved names.
pub fn validate_namespace_name(name: &str) -> Result<(), &'static str>;

/// Names that may not be used as a namespace in any Ankh consumer.
pub const SHARED_RESERVED_NAMES: &[&str] = _;
