// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-testdata
// Publish: crates.io
// Workspace dependencies: ankh-constants, ankh-db, ankh-types
// Workspace dependents: ankh-cli (dev), ankh-demo, ankh-web (dev)

//! Deterministic identity fixtures and shared test harness helpers.

use std::{fmt::Debug, path::Path, time::Duration};

use ankh_db::{AnkhDb, AnkhDbPool};
use ankh_types::{OrgId, OrgRole, UserId};
use chrono::{DateTime, Utc};
use uuid::Uuid;

/// Fixed clock used by deterministic tests.
#[derive(
    Clone,
    Copy,
    Debug,
    Default,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct FixedClock {/* private fields */}

impl FixedClock {
    /// Return the current fixed timestamp.
    #[must_use]
    pub const fn now(self) -> DateTime<Utc>;
}

/// Deterministic UUID generator used by scaffold tests and future harnesses.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct FixedIdGenerator {/* private fields */}

impl FixedIdGenerator {
    /// Create a generator from IDs that are returned in the provided order.
    #[must_use]
    pub fn new(ids: Vec<Uuid>) -> Self;

    /// Return the next deterministic ID.
    #[must_use]
    pub fn next_id(&mut self) -> Option<Uuid>;
}

/// Static mail fixture used by shared mail tests.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct MailFixture {
    /// Sender address.
    pub sender: &'static str,
    /// Support address.
    pub support: &'static str,
    /// Public base URL used in generated links.
    pub public_base_url: &'static str,
}

/// Static organization fixture used by shared org tests.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct OrgFixture {
    /// Organization namespace name.
    pub name: &'static str,
    /// Optional display name.
    pub display_name: Option<&'static str>,
    /// Owner user email.
    pub owner_email: &'static str,
    /// Members as `(email, role)` entries; owner is not repeated here.
    pub members: &'static [(&'static str, OrgRole)],
}

/// Static organization invite fixture used by shared invite tests.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct OrgInviteFixture {
    /// Organization namespace name.
    pub org_name: &'static str,
    /// Invited email address.
    pub email: &'static str,
    /// Role granted after invite acceptance.
    pub role: OrgRole,
    /// Deterministic raw invite token.
    pub token: &'static str,
}

/// IDs created by [`seed_identity_rows`].
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct SeededIdentityIds {
    /// Alice's user ID.
    pub alice_user_id: UserId,
    /// Bob's user ID.
    pub bob_user_id: UserId,
    /// Default organization ID.
    pub default_org_id: OrgId,
}

/// Static sysadmin fixture used by shared admin tests.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct SysadminFixture {
    /// Email address.
    pub email: &'static str,
    /// Plain-text password used by deterministic tests.
    pub password: &'static str,
}

/// Temporary directory helper reserved for Ankh harnesses.
#[derive(Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct TempDirHelper {/* private fields */}

impl TempDirHelper {
    /// Create a fresh temporary directory.
    pub fn new() -> std::io::Result<Self>;

    /// Return the temporary directory path.
    #[must_use]
    pub fn path(&self) -> &Path;
}

/// Static user fixture used by shared identity tests.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct UserFixture {
    /// Username / namespace name.
    pub username: &'static str,
    /// Email address.
    pub email: &'static str,
    /// Plain-text password used by deterministic tests.
    pub password: &'static str,
    /// Whether the email starts verified.
    pub verified: bool,
}

/// Seed deterministic shared identity rows through an Ankh pool.
pub async fn seed_identities(pool: AnkhDbPool) -> ankh_db::Result<()>;

/// Seed deterministic shared identity rows on an already checked-out handle.
pub async fn seed_identity_rows(db: &mut AnkhDb) -> ankh_db::Result<SeededIdentityIds>;

/// Primary sysadmin fixture.
pub const ADMIN: SysadminFixture = _;

/// Primary verified user fixture.
pub const ALICE: UserFixture = _;

/// Web-session token seeded for [`ALICE`].
pub const ALICE_SESSION_TOKEN: &str = "11111111-1111-1111-1111-111111111111";

/// Secondary unverified user fixture.
pub const BOB: UserFixture = _;

/// Web-session token seeded for [`BOB`].
pub const BOB_SESSION_TOKEN: &str = "22222222-2222-2222-2222-222222222222";

/// Default organization fixture.
pub const DEFAULT_ORG: OrgFixture = _;

/// Shared mail branding fixture.
pub const MAIL: MailFixture = _;

/// Pending organization invite fixture.
pub const PENDING_ORG_INVITE: OrgInviteFixture = _;

/// Default session expiry used for seeded accounts.
pub const SESSION_TTL: Duration = DEFAULT_SESSION_TTL;
