// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-mail
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ankh-cli (dev), ankh-demo, ankh-web

//! Transactional mail rendering, delivery, and test capture.

use std::{
    collections::HashMap,
    fmt::{Debug, Display},
    path::{Path, PathBuf},
    sync::Arc,
};

use chrono::{DateTime, Utc};

/// Mail delivery backend.
// Not dyn-compatible.
pub trait Mailer: Send + Sync {
    /// Send an email message.
    fn send(&self, email: &Email) -> impl Future<Output = crate::Result<()>> + Send;
}

/// Function used by [`DevMailer`] to get the current timestamp.
pub type Clock = Arc<dyn Fn() -> DateTime<Utc> + Send + Sync>;

/// Development mailer that persists messages to disk.
#[derive(Clone)]
pub struct DevMailer {/* private fields */}

impl DevMailer {
    /// Create a dev mailer that writes messages into `out_dir`.
    pub fn new(out_dir: impl Into<PathBuf>) -> Self;

    /// Read all emails written by this mailer, sorted by filename.
    pub fn read_all(&self) -> crate::Result<Vec<Email>>;

    /// Read the most recent email written by this mailer.
    pub fn read_latest(&self) -> crate::Result<Option<Email>>;

    /// Create a dev mailer with explicit clock and ID generator.
    pub fn with_config(config: DevMailerConfig) -> Self;
}

impl Mailer for DevMailer {}

/// Configuration for development mail artifacts.
#[derive(Clone)]
pub struct DevMailerConfig {
    /// Output directory for mail artifacts.
    pub out_dir: PathBuf,
    /// Clock used to timestamp artifacts.
    pub clock: Clock,
    /// Identifier generator used to keep artifact names unique.
    pub id_gen: IdGenerator,
}

impl DevMailerConfig {
    /// Build a dev mailer config using wall-clock time and UUID identifiers.
    pub fn new(out_dir: impl Into<PathBuf>) -> Self;
}

/// Provider-agnostic email message.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Email {
    /// Recipient address.
    pub to: String,
    /// Sender address.
    pub from: String,
    /// Message subject.
    pub subject: String,
    /// Plain-text message body.
    pub text_body: String,
    /// Optional HTML message body.
    pub html_body: Option<String>,
}

/// Error type used across mail rendering and delivery.
#[derive(Debug, Display, std::error::Error)]
pub enum Error {
    /// Public base URL is empty after normalization.
    #[error("public base url cannot be empty")]
    InvalidBaseUrl,
    /// Requested template name does not exist.
    #[error("template not found: {0}")]
    TemplateNotFound(String),
    /// Template contents are invalid.
    #[error("invalid template: {0}")]
    InvalidTemplate(String),
    /// Dev mail artifact on disk is malformed.
    #[error("invalid dev mail artifact: {0}")]
    InvalidDevMail(String),
    /// IO failure while writing or reading dev mail artifacts.
    #[error("mail io error: {0}")]
    Io(std::io::Error),
}

impl From<std::io::Error> for Error {}

/// Function used by [`DevMailer`] to create unique artifact identifiers.
pub type IdGenerator = Arc<dyn Fn() -> String + Send + Sync>;

/// Product mail branding applied to shared templates.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MailBranding {
    /// Product name inserted into shared templates.
    pub app_name: String,
    /// Public base URL used for absolute links.
    pub public_base_url: PublicBaseUrl,
    /// Default sender address used as [`Email::from`].
    pub sender: String,
    /// Support address exposed in templates and shells.
    pub support_address: String,
    /// Optional HTML shell that receives `{html_body}` plus branding
    /// placeholders.
    pub html_shell: Option<String>,
}

impl MailBranding {
    /// Construct an absolute action URL with a token query parameter.
    pub fn action_url(&self, path: &str, token: &str) -> String;

    /// Construct an absolute URL for a path.
    pub fn link_url(&self, path: &str) -> String;

    /// Build mail branding without an HTML shell.
    pub fn new(
        app_name: impl Into<String>,
        public_base_url: PublicBaseUrl,
        sender: impl Into<String>,
        support_address: impl Into<String>,
    ) -> Self;

    /// Return a copy of this branding with the supplied HTML shell.
    #[must_use]
    pub fn with_html_shell(self, html_shell: impl Into<String>) -> Self;
}

/// Shared transactional mail catalog with optional product overrides.
#[derive(Clone, Debug, Default)]
pub struct MailCatalog {/* private fields */}

impl MailCatalog {
    /// Render the named template into an addressed email.
    pub fn render_email(
        &self,
        template_name: &str,
        to: &str,
        branding: &MailBranding,
        vars: &HashMap<String, String>,
    ) -> crate::Result<Email>;

    /// Build a shared catalog with no product overrides.
    #[must_use]
    pub fn shared() -> Self;

    /// Build a shared catalog with product template overrides.
    pub fn with_overrides(overrides: impl IntoIterator<Item = (String, MailTemplate)>) -> Self;
}

/// Text and optional HTML source for a named mail template.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MailTemplate {
    /// Plain-text template source. The first line must be `Subject: ...`,
    /// followed by `---` on its own line and then the text body.
    pub text: String,
    /// Optional HTML template source.
    pub html: Option<String>,
}

impl MailTemplate {
    /// Build a mail template from text and optional HTML source.
    pub fn new(text: impl Into<String>, html: Option<impl Into<String>>) -> Self;
}

/// Mailer that silently drops every message.
///
/// Used in production deployments that intentionally send no mail (e.g. a
/// waitlist launch where signups are collected but no outbound email is sent).
/// Sending always succeeds, so callers that treat a send failure as fatal keep
/// working without a real provider configured.
#[derive(Clone, Copy, Debug, Default)]
pub struct NoopMailer;

impl NoopMailer {
    /// Create a no-op mailer.
    #[must_use]
    pub fn new() -> Self;
}

impl Mailer for NoopMailer {}

/// Base URL used to construct absolute links in mail.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PublicBaseUrl(_);

impl PublicBaseUrl {
    /// Construct an action URL with a `token` query parameter.
    pub fn action_url(&self, path: &str, token: &str) -> String;

    /// Join a path onto the base URL, trimming leading slashes.
    pub fn join(&self, path: &str) -> String;

    /// Normalize and validate a public base URL.
    pub fn new(value: impl Into<String>) -> crate::Result<Self>;
}

/// Cloneable in-memory sink for mail assertions in tests.
#[derive(Clone, Debug, Default)]
pub struct RecordingMailer {/* private fields */}

impl RecordingMailer {
    /// Create an empty recording mailer.
    #[must_use]
    pub fn new() -> Self;

    /// Record an email in memory.
    pub fn record(&self, email: Email);

    /// Return and clear every recorded email.
    #[must_use]
    pub fn take_sent(&self) -> Vec<Email>;
}

impl Mailer for RecordingMailer {}

/// Shorthand for mail operation results.
pub type Result<T> = Result<T, Error>;

/// Read all development emails from `out_dir`, sorted by filename.
///
/// Standalone reader for callers that do not hold a [`DevMailer`]; mirrors
/// [`DevMailer::read_all`].
pub fn read_all_dev_mail(out_dir: &Path) -> crate::Result<Vec<Email>>;

/// Read the most recent development email from `out_dir`.
///
/// Standalone reader for callers that do not hold a [`DevMailer`] (e.g.
/// inspecting artifacts written by another process); mirrors
/// [`DevMailer::read_latest`].
pub fn read_latest_dev_mail(out_dir: &Path) -> crate::Result<Option<Email>>;

pub mod template {
    //! Shared template names.

    /// Email verification template.
    pub const EMAIL_VERIFICATION: &str = "email_verification";

    /// Organization invite template.
    pub const ORG_INVITE: &str = "org_invite";

    /// Password reset template.
    pub const PASSWORD_RESET: &str = "password_reset";

    /// Waitlist invite template.
    pub const WAITLIST_INVITE: &str = "waitlist_invite";

    /// Waitlist release template.
    pub const WAITLIST_RELEASE: &str = "waitlist_release";
}
