// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-demo
// Publish: crates.io
// Binaries: ankh-demo
// Workspace dependencies: ankh-db, ankh-mail, ankh-testdata, ankh-web
// Workspace dependents: none

//! Library backing the local Ankh demo server.
//!
//! The demo wires the public and admin routers to a Postgres pool and a
//! [`DevMailer`], and serves the built `@ankh/demo-web` single-page app as the
//! fallback, so the whole identity stack can be exercised in isolation from the
//! leaf products — in a browser, by the `ankh-cli` admin client,
//! or by a frontend dev server proxied at the demo port. It is a development
//! and QA tool, not a production deployment.

use std::{error::Error, path::PathBuf};

use ankh_db::AnkhDbPool;
use ankh_testdata::SeededIdentityIds;
use axum::Router;

/// Build the merged public + admin router wired to demo-friendly state, with
/// the built `@ankh/demo-web` single-page app served as the fallback.
///
/// `base_url` should match the address the server will actually be reached at
/// so links in captured mail are clickable; `mail_dir` receives [`DevMailer`]
/// artifacts. Requests that match no API or admin route fall through to the SPA
/// at [`frontend_dist_dir`]; when that bundle has not been built (e.g.
/// `--no-frontend`), those requests simply 404.
pub fn build_app(
    pool: AnkhDbPool,
    base_url: &str,
    mail_dir: impl Into<PathBuf>,
) -> Result<Router, Box<dyn Error>>;

/// Directory the built `@ankh/demo-web` bundle is emitted to (see its
/// `vite.config.ts`).
pub fn frontend_dist_dir() -> PathBuf;

/// Print the login credentials produced by seeding.
pub fn report_seeded(ids: &SeededIdentityIds);

/// Database that `cargo xtask db start` provisions and the demo connects to.
pub const DEMO_DATABASE: &str = "ankh-test";

/// Directory the demo writes [`DevMailer`] artifacts into, relative to the
/// working directory.
pub const MAIL_OUT_DIR: &str = "tmp/mail";
