// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-web
// Publish: crates.io
// Workspace dependencies: ankh-constants, ankh-db, ankh-mail, ankh-names, ankh-types
// Workspace dependents: ankh-cli (dev), ankh-demo

//! Shared Ankh web services, extractors, routers, hooks, and audit seams.

use std::{
    collections::HashMap,
    error::Error,
    fmt::{Debug, Display},
    net::IpAddr,
    pin::Pin,
    sync::Arc,
};

use ankh_db::{AnkhDbPool, DeviceSession, Session, SysadminInfo};
use ankh_mail::{Email, MailBranding, MailCatalog, Mailer};
use ankh_types::{DeviceSessionId, NamespaceId, SysadminId, UserId};
use axum::{Router, http::HeaderMap};
use axum_core::{extract::FromRequestParts, response::into_response::IntoResponse};
use chrono::{DateTime, Utc};

/// Sink for admin audit events.
#[async_trait]
pub trait AdminAudit: Send + Sync {
    /// Record an admin audit event.
    async fn record(&self, event: AdminAuditEvent) -> Result<(), String>;
}

/// Object-safe mail transport used by web state.
#[async_trait]
pub trait MailTransport: Send + Sync {
    /// Send an email message.
    async fn send(&self, email: &Email) -> ankh_mail::Result<()>;
}

impl<T> MailTransport for T where T: Mailer + Send + Sync {}

/// Product cleanup hooks dispatched after successful Ankh-owned mutations.
#[async_trait]
pub trait ProductHooks: Send + Sync {
    /// Called after device sessions have been revoked.
    async fn on_device_sessions_revoked(
        &self,
        payload: DeviceSessionsRevoked,
    ) -> Result<(), String>;

    /// Called after a namespace has been reinstated.
    async fn on_namespace_reinstated(&self, payload: NamespaceStatusChanged) -> Result<(), String>;

    /// Called after a namespace has been suspended.
    async fn on_namespace_suspended(&self, payload: NamespaceStatusChanged) -> Result<(), String>;

    /// Called before or after namespaces are deleted, depending on the owning
    /// product path.
    async fn on_namespaces_deleted(&self, payload: Vec<NamespaceDeleted>) -> Result<(), String>;

    /// Called after an organization member has been removed.
    async fn on_org_member_removed(&self, payload: OrgMemberRemoved) -> Result<(), String>;
}

/// Audit event representing an admin operation.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AdminAuditEvent {
    /// Admin ID that performed the action, when known.
    pub sysadmin_id: Option<SysadminId>,
    /// Action performed, for example `user.delete`.
    pub action: &'static str,
    /// Type of target entity, for example `user`.
    pub target_type: &'static str,
    /// ID or stable selector for the target entity.
    pub target_id: String,
    /// Request ID for correlation.
    pub request_id: String,
    /// Client IP address.
    pub ip: Option<IpAddr>,
    /// Client user agent.
    pub user_agent: Option<String>,
    /// When the event occurred.
    pub occurred_at: DateTime<Utc>,
    /// Result of the operation.
    pub result: AdminAuditResult,
}

impl AdminAuditEvent {
    /// Build an audit event from request context.
    #[must_use]
    pub fn new(
        sysadmin_id: Option<SysadminId>,
        action: &'static str,
        target_type: &'static str,
        target_id: impl Into<String>,
        result: AdminAuditResult,
        ctx: &RequestContext,
    ) -> Self;
}

/// Result label recorded for an admin operation.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub enum AdminAuditResult {
    /// Operation succeeded.
    Success,
    /// Operation failed.
    Failure,
}

impl AdminAuditResult {
    /// Return the stable text value for this result.
    #[must_use]
    pub const fn as_str(self) -> &'static str;
}

impl From<bool> for AdminAuditResult {}

/// Admin API error type that can be converted into an HTTP response.
#[derive(Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AdminError {/* private fields */}

impl AdminError {
    /// Create a 400 Bad Request error.
    #[must_use]
    pub fn bad_request(message: impl Into<String>) -> Self;

    /// Create a 409 Conflict error.
    #[must_use]
    pub fn conflict(message: impl Into<String>) -> Self;

    /// Create a 403 Forbidden error.
    #[must_use]
    pub fn forbidden(message: impl Into<String>) -> Self;

    /// Create a 500 Internal Server Error.
    #[must_use]
    pub fn internal(message: impl Into<String>) -> Self;

    /// Create a 404 Not Found error.
    #[must_use]
    pub fn not_found(message: impl Into<String>) -> Self;

    /// Create a 429 Too Many Requests error.
    #[must_use]
    pub fn rate_limited(message: impl Into<String>) -> Self;

    /// Create a 401 Unauthorized error.
    #[must_use]
    pub fn unauthorized(message: impl Into<String>) -> Self;

    /// Attach a request ID to the error response.
    #[must_use]
    pub fn with_request_id(self, request_id: impl Into<String>) -> Self;
}

impl IntoResponse for AdminError {}

/// Result type for admin API handlers.
pub type AdminResult<T> = Result<T, AdminError>;

/// Shared Ankh web configuration.
#[derive(
    Clone,
    Debug,
    Default,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct AnkhWebConfig {
    /// Cookie behavior.
    pub cookie: CookieConfig,
    /// Device authorization behavior.
    pub device_auth: DeviceAuthConfig,
}

/// Shared state required by the mountable Ankh public routers.
#[derive(Clone, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AnkhWebState {/* private fields */}

impl AnkhWebState {
    /// Return the installed admin audit sink.
    #[must_use]
    pub fn admin_audit(&self) -> Arc<dyn AdminAudit>;

    /// Return the runtime web configuration.
    #[must_use]
    pub fn config(&self) -> &AnkhWebConfig;

    /// Return the Ankh identity database pool.
    #[must_use]
    pub fn db_pool(&self) -> &AnkhDbPool;

    /// Return the installed product hooks.
    #[must_use]
    pub fn hooks(&self) -> Arc<dyn ProductHooks>;

    /// Return the shared mail state.
    #[must_use]
    pub fn mail(&self) -> &MailState;

    /// Build shared web state with default config and no-op hooks.
    #[must_use]
    pub fn new(db_pool: AnkhDbPool, mail: MailState) -> Self;

    /// Record a best-effort admin audit failure.
    pub fn record_audit_failure(&self, label: impl Into<String>, error: impl Into<String>);

    /// Record a best-effort hook failure.
    pub fn record_hook_failure(&self, label: impl Into<String>, error: impl Into<String>);

    /// Return and clear recorded admin audit failures.
    #[must_use]
    pub fn take_audit_failures(&self) -> Vec<String>;

    /// Return and clear recorded hook failures.
    #[must_use]
    pub fn take_hook_failures(&self) -> Vec<String>;

    /// Return a copy of this state with an admin audit sink installed.
    #[must_use]
    pub fn with_admin_audit(self, admin_audit: Arc<dyn AdminAudit>) -> Self;

    /// Build shared web state with explicit config and no-op hooks.
    #[must_use]
    pub fn with_config(db_pool: AnkhDbPool, mail: MailState, config: AnkhWebConfig) -> Self;

    /// Return a copy of this state with product hooks installed.
    #[must_use]
    pub fn with_hooks(self, hooks: Arc<dyn ProductHooks>) -> Self;
}

/// Public API error type that can be converted into an HTTP response.
#[derive(Debug, Display, Error, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ApiError {/* private fields */}

impl ApiError {
    /// Create a 400 Bad Request error.
    #[must_use]
    pub fn bad_request(message: impl Into<String>) -> Self;

    /// Create a 409 Conflict error.
    #[must_use]
    pub fn conflict(message: impl Into<String>) -> Self;

    /// Create a 403 Forbidden error.
    #[must_use]
    pub fn forbidden(message: impl Into<String>) -> Self;

    /// Create a 500 Internal Server Error.
    #[must_use]
    pub fn internal(message: impl Into<String>) -> Self;

    /// Create a 404 Not Found error.
    #[must_use]
    pub fn not_found(message: impl Into<String>) -> Self;

    /// Create a 429 Too Many Requests error.
    #[must_use]
    pub fn too_many_requests(message: impl Into<String>) -> Self;

    /// Create a 401 Unauthorized error.
    #[must_use]
    pub fn unauthorized(message: impl Into<String>) -> Self;
}

impl IntoResponse for ApiError {}

/// Result type for public API handlers.
pub type ApiResult<T> = Result<T, ApiError>;

/// Extracted auth session, if available.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AuthSession(pub Option<Session>);

impl<S> FromRequestParts<S> for AuthSession
where
    S: Send + Sync,
{
    type Rejection = ApiError;
}

/// Cookie behavior for browser web sessions.
#[derive(
    Clone,
    Debug,
    Default,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct CookieConfig {
    /// Cookie name used for web sessions.
    pub session_cookie_name: String,
    /// Whether the session cookie should carry the Secure attribute.
    pub secure: bool,
}

/// Device authorization route configuration.
#[derive(
    Clone,
    Debug,
    Default,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct DeviceAuthConfig {
    /// Browser login path used when a device authorize request has no web
    /// session.
    pub login_path: String,
}

/// Extractor that requires a valid device bearer session.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct DeviceBearerSession(pub DeviceSession);

impl<S> FromRequestParts<S> for DeviceBearerSession
where
    S: Send + Sync,
{
    type Rejection = ApiError;
}

/// Hook payload for one or more device-session revocations.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct DeviceSessionsRevoked {
    /// User that owned the revoked sessions.
    pub user_id: UserId,
    /// Revoked device session IDs.
    pub session_ids: Vec<DeviceSessionId>,
}

/// Record-only audit sink used by Ankh web harness tests.
#[derive(Clone, Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct FakeAuditSink {/* private fields */}

impl FakeAuditSink {
    /// Create an empty audit sink.
    #[must_use]
    pub fn new() -> Self;

    /// Record an audit event label.
    pub fn record(&self, event: impl Into<String>);

    /// Return and clear every recorded audit event.
    #[must_use]
    pub fn take_events(&self) -> Vec<String>;
}

impl AdminAudit for FakeAuditSink {}

/// Record-only hook sink used by Ankh web harness tests.
#[derive(Clone, Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct FakeHookRecorder {/* private fields */}

impl FakeHookRecorder {
    /// Create an empty hook recorder.
    #[must_use]
    pub fn new() -> Self;

    /// Record a hook call label.
    pub fn record(&self, call: impl Into<String>);

    /// Return and clear every recorded hook call.
    #[must_use]
    pub fn take_calls(&self) -> Vec<String>;
}

impl ProductHooks for FakeHookRecorder {}

/// Mail renderer and transport for shared Ankh services.
#[derive(Clone, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct MailState {/* private fields */}

impl MailState {
    /// Construct an absolute action URL with a token query parameter.
    #[must_use]
    pub fn action_url(&self, path: &str, token: &str) -> String;

    /// Build mail state from an already shared transport.
    #[must_use]
    pub fn from_transport(
        transport: Arc<dyn MailTransport>,
        catalog: MailCatalog,
        branding: MailBranding,
    ) -> Self;

    /// Construct an absolute URL for a path.
    #[must_use]
    pub fn link_url(&self, path: &str) -> String;

    /// Build mail state from a concrete mailer, catalog, and product branding.
    #[must_use]
    pub fn new<T>(transport: T, catalog: MailCatalog, branding: MailBranding) -> Self
    where
        T: 'static + MailTransport;

    /// Render a named template into an email.
    pub fn render_email(
        &self,
        template_name: &str,
        recipient: &str,
        vars: &HashMap<String, String>,
    ) -> ApiResult<Email>;

    /// Send a rendered email.
    pub async fn send(&self, email: &Email) -> ApiResult<()>;
}

/// Hook payload for namespace deletion.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct NamespaceDeleted {
    /// Namespace ID.
    pub namespace_id: NamespaceId,
    /// Namespace name.
    pub namespace: String,
}

/// Hook payload for namespace suspension state changes.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct NamespaceStatusChanged {
    /// Namespace ID.
    pub namespace_id: NamespaceId,
    /// Namespace name.
    pub namespace: String,
    /// Whether the namespace is now suspended.
    pub suspended: bool,
    /// Edge-visible generation after the update.
    pub r#gen: i64,
}

/// No-op hook sink used by products that have no cleanup to run.
#[derive(Clone, Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct NoopProductHooks;

impl ProductHooks for NoopProductHooks {}

/// Hook payload for removing a user from an organization namespace.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct OrgMemberRemoved {
    /// Organization namespace name.
    pub namespace: String,
    /// Removed user ID.
    pub user_id: UserId,
}

/// Request context extractor for audit logging.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct RequestContext {
    /// Request ID for correlation.
    pub request_id: String,
    /// Client IP address.
    pub ip: Option<IpAddr>,
    /// Client user agent.
    pub user_agent: Option<String>,
}

impl<S> FromRequestParts<S> for RequestContext
where
    S: Send + Sync,
{
    type Rejection = never;
}

/// Extractor that requires a valid web session for a non-waitlisted user.
///
/// Resolves the session like [`RequireSession`], then rejects with 403 when the
/// account is waitlisted. Use this on product routes that a waitlisted user
/// must not reach; use [`RequireSession`] for routes a waitlisted user still
/// needs (e.g. `me`, `logout`, waitlist status).
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct RequireActiveUser(pub Session);

impl<S> FromRequestParts<S> for RequireActiveUser
where
    S: Send + Sync,
{
    type Rejection = ApiError;
}

/// Extractor that requires a valid web session.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct RequireSession(pub Session);

impl<S> FromRequestParts<S> for RequireSession
where
    S: Send + Sync,
{
    type Rejection = ApiError;
}

/// Extractor that validates an admin bearer token and provides the sysadmin
/// info.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct SysadminAuth(pub SysadminInfo);

impl<S> FromRequestParts<S> for SysadminAuth
where
    S: Send + Sync,
{
    type Rejection = AdminError;
}

/// Build the mountable Ankh admin router under `/admin/v1`.
pub fn admin_router() -> Router;

/// Extract a bearer token from request headers.
pub fn bearer_token(headers: &HeaderMap) -> Result<String, ApiError>;

/// Emit an audit event and record best-effort failures on shared state.
pub async fn emit_admin_audit(state: &AnkhWebState, event: AdminAuditEvent);

/// Build the mountable Ankh public API router.
pub fn router<S>() -> Router<S>
where
    S: 'static + Clone + Send + Sync;

pub mod test_support {
    //! In-process router and application harness used by tests and the demo server.
    //! In-process web harness helpers for Ankh router tests.

    /// In-process Ankh public router harness.
    #[derive(Clone, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct TestAppHarness {/* private fields */}

    impl TestAppHarness {
        /// Build a harness around a caller-supplied state object.
        #[must_use]
        pub fn new(state: AnkhWebState) -> Self;

        /// Return the mounted router.
        pub fn router(&self) -> Router;

        /// Return the shared web state.
        #[must_use]
        pub fn state(&self) -> &AnkhWebState;
    }
}
