// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-db
// Publish: crates.io
// Workspace dependencies: ankh-constants, ankh-names, ankh-types
// Workspace dependents: ankh-cli (dev), ankh-demo, ankh-testdata, ankh-web, ankh-xtask

//! Canonical Ankh identity database schema and query layer.

use std::{
    fmt::{Debug, Display},
    time::Duration,
};

use ankh_names::NamePolicy;
pub use ankh_types::{
    DeviceAuthGrantId, DevicePlatform, DeviceSessionId, NamespaceId, NamespaceKind, OrgId,
    OrgInviteId, OrgRole, SessionId, SysadminId, UserId,
};
use ankh_types::{
    DeviceAuthGrantId, DevicePlatform, DeviceSessionId, NamespaceId, OrgId, OrgInviteId, OrgRole,
    SessionId, SysadminId, UserId,
};
use chrono::{DateTime, Utc};
use deadpool_postgres::Object;
use tokio_postgres::Client;
use uuid::Uuid;
/// Concrete Postgres-backed Ankh identity database handle.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AnkhDb {/* private fields */}

impl AnkhDb {
    /// Accept an organization invite.
    pub async fn accept_org_invite(&self, token: &str, user_id: UserId) -> crate::Result<()>;

    /// Add an organization member.
    pub async fn add_org_member(
        &self,
        org_id: OrgId,
        user_id: UserId,
        role: OrgRole,
        added_by: Option<UserId>,
    ) -> crate::Result<()>;

    /// Add a web session with a caller-provided token.
    pub async fn add_session(
        &self,
        session_id: &str,
        email: &str,
        ttl: Duration,
    ) -> crate::Result<()>;

    /// Create a sysadmin.
    pub async fn add_sysadmin(&self, email: &str, password: &str) -> crate::Result<SysadminId>;

    /// Add a user with a freshly hashed password.
    pub async fn add_user(
        &mut self,
        username: &str,
        email: &str,
        password: &str,
    ) -> crate::Result<()>;

    /// Apply the canonical Ankh identity schema to this database.
    pub async fn apply_schema(&self) -> crate::Result<()>;

    /// Apply the canonical Ankh identity schema to a raw Postgres client.
    pub async fn apply_schema_to_client(client: &Client) -> crate::Result<()>;

    /// Apply schema and initialize the database for Ankh identity operations.
    pub async fn bootstrap(&self) -> crate::Result<()>;

    /// Cancel an organization invite.
    pub async fn cancel_org_invite(&self, invite_id: OrgInviteId) -> crate::Result<()>;

    /// Return the underlying checked-out Postgres client for colocated product
    /// SQL.
    #[must_use]
    pub fn client(&self) -> &Client;

    /// Return the mutable underlying checked-out Postgres client for colocated
    /// product SQL.
    pub fn client_mut(&mut self) -> &mut Client;

    /// Consume a device authorization grant.
    pub async fn consume_device_auth_grant(
        &mut self,
        code: &str,
        code_verifier: &str,
    ) -> crate::Result<DeviceAuthGrant>;

    /// Consume an account invite.
    pub async fn consume_invite(&self, token: &str) -> crate::Result<String>;

    /// Consume a one-time identity token.
    pub async fn consume_token(&mut self, token: &str, kind: TokenKind) -> crate::Result<String>;

    /// Create a device authorization grant.
    pub async fn create_device_auth_grant(
        &self,
        request: DeviceAuthGrantRequest<'_>,
    ) -> crate::Result<CreatedDeviceAuthGrant>;

    /// Create a device session.
    pub async fn create_device_session(
        &self,
        user_id: UserId,
        device_name: &str,
        platform: &DevicePlatform,
        ttl: Duration,
    ) -> crate::Result<CreatedDeviceSession>;

    /// Create an account invite.
    pub async fn create_invite(&self, email: &str, ttl: Duration) -> crate::Result<String>;

    /// Create an organization.
    pub async fn create_org(
        &mut self,
        name: &str,
        display_name: Option<&str>,
        created_by: UserId,
    ) -> crate::Result<OrgId>;

    /// Create an organization invite.
    pub async fn create_org_invite(
        &self,
        org_id: OrgId,
        email: &str,
        invited_by: UserId,
        ttl: Duration,
    ) -> crate::Result<(String, OrgInviteId)>;

    /// Create an organization invite with a caller-supplied token.
    pub async fn create_org_invite_with_token(
        &self,
        org_id: OrgId,
        email: &str,
        invited_by: UserId,
        ttl: Duration,
        token: &str,
    ) -> crate::Result<OrgInviteId>;

    /// Create an organization while allowing reserved namespace words.
    pub async fn create_org_unchecked(
        &mut self,
        name: &str,
        display_name: Option<&str>,
        created_by: UserId,
    ) -> crate::Result<OrgId>;

    /// Create a one-time identity token.
    pub async fn create_token(
        &self,
        email: &str,
        kind: TokenKind,
        ttl: Duration,
    ) -> crate::Result<String>;

    /// Delete expired organization invites.
    pub async fn delete_expired_org_invites(&self) -> crate::Result<u64>;

    /// Delete expired web sessions.
    pub async fn delete_expired_sessions(&self) -> crate::Result<u64>;

    /// Delete expired sysadmin bearer tokens.
    pub async fn delete_expired_sysadmin_tokens(&self) -> crate::Result<u64>;

    /// Delete expired one-time identity tokens.
    pub async fn delete_expired_tokens(&self) -> crate::Result<u64>;

    /// Delete account invites for an email address.
    pub async fn delete_invites_for_email(&self, email: &str) -> crate::Result<()>;

    /// Delete an organization.
    pub async fn delete_org(&self, id: OrgId) -> crate::Result<()>;

    /// Delete a web session.
    pub async fn delete_session(&self, session_id: &str) -> crate::Result<()>;

    /// Delete all web sessions for a user email.
    pub async fn delete_sessions_for_email(&self, email: &str) -> crate::Result<u64>;

    /// Delete tokens for a user email and kind.
    pub async fn delete_tokens_for_email(&self, email: &str, kind: TokenKind) -> crate::Result<()>;

    /// Delete a user by email address.
    pub async fn delete_user(&self, email: &str) -> crate::Result<()>;

    /// Delete a user by ID.
    pub async fn delete_user_by_id(&self, id: UserId) -> crate::Result<()>;

    /// Ensure the singleton Ankh settings row exists.
    pub async fn ensure_settings_row(&self) -> crate::Result<()>;

    /// Ensure the singleton Ankh settings row exists on a raw Postgres client.
    pub async fn ensure_settings_row_on_client(client: &Client) -> crate::Result<()>;

    /// Return the global identity settings.
    pub async fn get_app_settings(&self) -> crate::Result<AppSettings>;

    /// Get a device session by ID.
    pub async fn get_device_session(&self, id: DeviceSessionId) -> crate::Result<DeviceSession>;

    /// Get an organization by ID.
    pub async fn get_org_by_id(&self, id: OrgId) -> crate::Result<OrgDetail>;

    /// Get an organization by name.
    pub async fn get_org_by_name(&self, name: &str) -> crate::Result<OrgDetail>;

    /// Get an organization invite by raw token.
    pub async fn get_org_invite(&self, token: &str) -> crate::Result<OrgInvite>;

    /// Get an organization member.
    pub async fn get_org_member(&self, org_id: OrgId, user_id: UserId) -> crate::Result<OrgMember>;

    /// Get the owner member for an organization.
    pub async fn get_org_owner(&self, org_id: OrgId) -> crate::Result<OrgMember>;

    /// Get a web session.
    pub async fn get_session(&self, session_id: &str) -> crate::Result<Session>;

    /// Get a sysadmin by ID.
    pub async fn get_sysadmin(&self, id: SysadminId) -> crate::Result<SysadminInfo>;

    /// Get a user by email address.
    pub async fn get_user_by_email(&self, email: &str) -> crate::Result<UserDetail>;

    /// Get a user by ID.
    pub async fn get_user_by_id(&self, id: UserId) -> crate::Result<UserDetail>;

    /// Get a user by username.
    pub async fn get_user_by_name(&self, username: &str) -> crate::Result<UserDetail>;

    /// Record the current schema version and ensure singleton settings exist.
    pub async fn initialize(&self) -> crate::Result<()>;

    /// Initialize Ankh identity metadata on a raw Postgres client.
    pub async fn initialize_client(client: &Client) -> crate::Result<()>;

    /// Return whether a user's email has been verified.
    pub async fn is_email_verified(&self, email: &str) -> crate::Result<bool>;

    /// Return whether an organization has no non-owner members.
    pub async fn is_org_empty(&self, id: OrgId) -> crate::Result<bool>;

    /// Return whether a user is waitlisted.
    pub async fn is_user_waitlisted(&self, email: &str) -> crate::Result<bool>;

    /// Return the newest token creation timestamp for a user and kind.
    pub async fn latest_token_created_at(
        &self,
        email: &str,
        kind: TokenKind,
    ) -> crate::Result<Option<DateTime<Utc>>>;

    /// List organizations for admin views.
    pub async fn list_all_orgs(
        &self,
        limit: i64,
        cursor: Option<&str>,
    ) -> crate::Result<(Vec<OrgSummary>, Option<String>)>;

    /// List device sessions for admin views.
    pub async fn list_device_sessions(
        &self,
        limit: i64,
        cursor: Option<&str>,
        user_id: Option<UserId>,
        status: Option<DeviceSessionStatus>,
    ) -> crate::Result<(Vec<DeviceSessionSummary>, Option<String>)>;

    /// List active device sessions for a user.
    pub async fn list_device_sessions_for_user(
        &self,
        user_id: UserId,
    ) -> crate::Result<Vec<DeviceSession>>;

    /// List organization invites.
    pub async fn list_org_invites(&self, org_id: OrgId) -> crate::Result<Vec<OrgInvite>>;

    /// List organization members.
    pub async fn list_org_members(&self, org_id: OrgId) -> crate::Result<Vec<OrgMember>>;

    /// List organizations for a user.
    pub async fn list_orgs_for_user(&self, user_id: UserId) -> crate::Result<Vec<OrgSummary>>;

    /// List web sessions for admin views.
    pub async fn list_sessions(
        &self,
        limit: i64,
        cursor: Option<&str>,
        user_id: Option<UserId>,
        status: Option<SessionStatus>,
    ) -> crate::Result<(Vec<SessionSummary>, Option<String>)>;

    /// List sysadmins for admin views.
    pub async fn list_sysadmins(
        &self,
        limit: i64,
        cursor: Option<&str>,
    ) -> crate::Result<(Vec<SysadminInfo>, Option<String>)>;

    /// List users for admin views.
    pub async fn list_users(
        &self,
        limit: i64,
        cursor: Option<&str>,
        email_filter: Option<&str>,
    ) -> crate::Result<(Vec<UserSummary>, Option<String>)>;

    /// Mark a user's email verified.
    pub async fn mark_email_verified(&self, email: &str) -> crate::Result<()>;

    /// Build an Ankh DB handle from a checked-out pool object.
    #[must_use]
    pub fn new(client: Object) -> Self;

    /// Peek an account invite.
    pub async fn peek_invite(&self, token: &str) -> crate::Result<String>;

    /// Peek a one-time identity token.
    pub async fn peek_token(&self, token: &str, kind: TokenKind) -> crate::Result<String>;

    /// Remove an organization member.
    pub async fn remove_org_member(&self, org_id: OrgId, user_id: UserId) -> crate::Result<()>;

    /// Revoke all device sessions for a user.
    pub async fn revoke_all_device_sessions(&self, user_id: UserId) -> crate::Result<u64>;

    /// Revoke a device session belonging to a user.
    pub async fn revoke_device_session(
        &self,
        id: DeviceSessionId,
        user_id: UserId,
    ) -> crate::Result<()>;

    /// Revoke a device session by ID.
    pub async fn revoke_device_session_by_id(&self, id: DeviceSessionId) -> crate::Result<()>;

    /// Revoke a web session by ID.
    pub async fn revoke_session_by_id(&self, id: SessionId) -> crate::Result<()>;

    /// Revoke a sysadmin bearer token.
    pub async fn revoke_sysadmin_token(&self, token: &str) -> crate::Result<()>;

    /// Set namespace suspension state and bump its edge-visible generation.
    pub async fn set_namespace_suspended(
        &self,
        namespace_id: NamespaceId,
        suspended: bool,
    ) -> crate::Result<NamespaceStatusUpdate>;

    /// Change an organization member role.
    pub async fn set_org_member_role(
        &self,
        org_id: OrgId,
        user_id: UserId,
        role: OrgRole,
    ) -> crate::Result<()>;

    /// Set a user's password.
    pub async fn set_password(&self, email: &str, password: &str) -> crate::Result<()>;

    /// Set whether a user is waitlisted.
    pub async fn set_user_waitlisted(&self, email: &str, waitlisted: bool) -> crate::Result<()>;

    /// Update the waitlist setting.
    pub async fn set_waitlist_enabled(&self, enabled: bool) -> crate::Result<AppSettings>;

    /// Sign in and create a web session.
    pub async fn signin(
        &self,
        identifier: &str,
        password: &str,
        ttl: Duration,
    ) -> crate::Result<String>;

    /// Sign in a sysadmin.
    pub async fn sysadmin_login(
        &self,
        email: &str,
        password: &str,
        ttl: Duration,
    ) -> crate::Result<(String, SysadminInfo)>;

    /// Touch a web session.
    pub async fn touch_session(&self, session_id: &str) -> crate::Result<Session>;

    /// Touch a web session only if it is stale.
    pub async fn touch_session_if_stale(
        &mut self,
        session_id: &str,
        stale_after: Duration,
    ) -> crate::Result<Session>;

    /// Transfer organization ownership.
    pub async fn transfer_org_ownership(
        &self,
        org_id: OrgId,
        new_owner_id: UserId,
    ) -> crate::Result<()>;

    /// Update an organization.
    pub async fn update_org(&self, id: OrgId, display_name: Option<&str>) -> crate::Result<()>;

    /// Validate a device session bearer token.
    pub async fn validate_device_session(&self, token: &str) -> crate::Result<DeviceSession>;

    /// Validate a sysadmin bearer token.
    pub async fn validate_sysadmin_token(&self, token: &str) -> crate::Result<SysadminInfo>;

    /// Read the newest applied Ankh schema version.
    pub async fn version(&self) -> crate::Result<Option<i32>>;

    /// Build an Ankh DB handle from a checked-out pool object and explicit
    /// config.
    #[must_use]
    pub fn with_config(client: Object, config: AnkhDbConfig) -> Self;
}

/// Configuration attached to an Ankh database handle.
#[derive(Clone, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AnkhDbConfig {
    /// Password hashing configuration for newly created credentials.
    pub password_hashing: PasswordHashing,
    /// Namespace validation policy for user and organization names.
    pub name_policy: NamePolicy,
}

/// Connection pool type for Postgres-backed Ankh identity data.
#[derive(Clone, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AnkhDbPool {/* private fields */}

impl AnkhDbPool {
    /// Fetch a pooled Ankh database connection.
    pub async fn get(&self) -> crate::Result<AnkhDb>;
}

/// Global identity settings stored in the database.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct AppSettings {
    /// Whether waitlist mode is enabled.
    pub waitlist_enabled: bool,
}

/// Result of creating a device authorization grant, including the raw code.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct CreatedDeviceAuthGrant {
    /// Unique identifier for the grant.
    pub id: DeviceAuthGrantId,
    /// Raw authorization code shown only once.
    pub code: String,
}

/// Result of creating a device session, including the raw token.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct CreatedDeviceSession {
    /// Device session metadata.
    pub session: DeviceSession,
    /// Raw device session token shown only once.
    pub token: String,
}

/// Pending device authorization grant stored in the database.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct DeviceAuthGrant {
    /// Unique identifier for the grant.
    pub id: DeviceAuthGrantId,
    /// User who authorized the grant.
    pub user_id: UserId,
    /// PKCE code challenge.
    pub code_challenge: String,
    /// State parameter echoed to the redirect.
    pub state: String,
    /// Loopback redirect port.
    pub redirect_port: i32,
    /// Device label supplied by the client.
    pub device_name: String,
    /// Platform that initiated the request.
    pub platform: DevicePlatform,
    /// Number of failed exchange attempts.
    pub attempts: i32,
    /// When the grant was created.
    pub created_at: DateTime<Utc>,
    /// When the grant expires.
    pub expires_at: DateTime<Utc>,
    /// When the grant was consumed, if ever.
    pub consumed_at: Option<DateTime<Utc>>,
}

/// Input data for creating a device authorization grant.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct DeviceAuthGrantRequest<'a> {
    /// User who authorized the grant.
    pub user_id: UserId,
    /// PKCE code challenge.
    pub code_challenge: &'a str,
    /// State parameter echoed to the redirect.
    pub state: &'a str,
    /// Loopback redirect port.
    pub redirect_port: i32,
    /// Device label supplied by the client.
    pub device_name: &'a str,
    /// Platform that initiated the request.
    pub platform: DevicePlatform,
    /// Time-to-live for the grant.
    pub ttl: Duration,
}

/// Device session metadata stored in the database.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct DeviceSession {
    /// Unique identifier for the session.
    pub id: DeviceSessionId,
    /// User that owns this session.
    pub user_id: UserId,
    /// Device label supplied by the client.
    pub device_name: String,
    /// Platform for the session.
    pub platform: DevicePlatform,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last-used timestamp.
    pub last_used_at: DateTime<Utc>,
    /// Absolute expiry timestamp.
    pub expires_at: DateTime<Utc>,
    /// When the session was revoked, if revoked.
    pub revoked_at: Option<DateTime<Utc>>,
}

/// Device session status for filtering.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub enum DeviceSessionStatus {
    /// Session is active.
    Active,
    /// Session has been revoked.
    Revoked,
    /// Session has expired.
    Expired,
}

/// Summary device session information for listing.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct DeviceSessionSummary {
    /// Unique identifier for the session.
    pub id: DeviceSessionId,
    /// User ID that owns this session.
    pub user_id: UserId,
    /// User email.
    pub user_email: String,
    /// Device label supplied by the client.
    pub device_name: String,
    /// Platform for the session.
    pub platform: DevicePlatform,
    /// When the session was created.
    pub created_at: DateTime<Utc>,
    /// When the session was last used.
    pub last_used_at: DateTime<Utc>,
    /// When the session expires.
    pub expires_at: DateTime<Utc>,
    /// When the session was revoked, if ever.
    pub revoked_at: Option<DateTime<Utc>>,
}

/// Errors returned by Ankh database operations.
#[derive(
    Debug,
    Display,
    std::error::Error,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub enum Error {
    /// Postgres connection parameters could not be parsed.
    #[error("invalid postgres config: {0}")]
    InvalidPostgresConfig(String),
    /// The Postgres pool could not be built.
    #[error("postgres pool build error: {0}")]
    PoolBuild(deadpool_postgres::BuildError),
    /// A pooled Postgres client could not be checked out.
    #[error("postgres pool error: {0}")]
    Pool(deadpool_postgres::PoolError),
    /// Password hashing failed.
    #[error("password hashing failed: {0}")]
    PasswordHash(password_hash::errors::Error),
    /// Stored waitlist status is not recognized.
    #[error("invalid waitlist status: {0}")]
    InvalidWaitlistStatus(String),
    /// No schema version has been recorded yet.
    #[error("schema version not set")]
    SchemaVersionMissing,
    /// Email already exists when attempting to create a user.
    #[error("user {0} already exists")]
    UserExists(String),
    /// Requested user could not be found.
    #[error("user {0} not found")]
    UserMissing(String),
    /// Requested session could not be found.
    #[error("session {0} not found")]
    SessionMissing(String),
    /// Session already exists when attempting to create one.
    #[error("session {0} already exists")]
    SessionExists(String),
    /// Device auth grant could not be found.
    #[error("device auth grant {0} not found")]
    DeviceAuthGrantMissing(String),
    /// Device auth grant has expired.
    #[error("device auth grant {0} expired")]
    DeviceAuthGrantExpired(String),
    /// Device auth grant was already consumed.
    #[error("device auth grant {0} already consumed")]
    DeviceAuthGrantConsumed(String),
    /// Device auth grant exceeded allowed attempts.
    #[error("device auth grant {0} attempts exceeded")]
    DeviceAuthGrantAttemptsExceeded(String),
    /// Device auth grant verifier did not match.
    #[error("device auth grant {0} verifier mismatch")]
    DeviceAuthGrantInvalidVerifier(String),
    /// Device session could not be found.
    #[error("device session {0} not found")]
    DeviceSessionMissing(String),
    /// Device session has expired.
    #[error("device session {0} expired")]
    DeviceSessionExpired(String),
    /// Device session has been revoked.
    #[error("device session {0} revoked")]
    DeviceSessionRevoked(String),
    /// Device session limit reached for user.
    #[error("device session limit reached for user {0}")]
    DeviceSessionLimitReached(String),
    /// Authentication failed due to invalid credentials.
    #[error("invalid credentials")]
    InvalidCredentials,
    /// Token could not be found.
    #[error("token not found: {0}")]
    TokenNotFound(String),
    /// Token is present but has expired.
    #[error("token expired: {0}")]
    TokenExpired(String),
    /// Invite token could not be found.
    #[error("invite not found: {0}")]
    InviteNotFound(String),
    /// Invite token is present but has expired.
    #[error("invite expired: {0}")]
    InviteExpired(String),
    /// Operation requires a verified email address.
    #[error("email not verified: {0}")]
    EmailNotVerified(String),
    /// Sysadmin account with this email already exists.
    #[error("sysadmin {0} already exists")]
    SysadminExists(String),
    /// Requested sysadmin account could not be found.
    #[error("sysadmin {0} not found")]
    SysadminMissing(String),
    /// Sysadmin token could not be found or is invalid.
    #[error("sysadmin token not found: {0}")]
    SysadminTokenNotFound(String),
    /// Sysadmin token is present but has expired.
    #[error("sysadmin token expired: {0}")]
    SysadminTokenExpired(String),
    /// Sysadmin account is disabled.
    #[error("sysadmin account disabled: {0}")]
    SysadminDisabled(String),
    /// Namespace name already exists.
    #[error("namespace {0} already exists")]
    NamespaceExists(String),
    /// Requested namespace could not be found.
    #[error("namespace {0} not found")]
    NamespaceMissing(String),
    /// Invalid namespace name.
    #[error("invalid namespace name: {0}")]
    InvalidNamespaceName(&'static str),
    /// Organization could not be found.
    #[error("organization {0} not found")]
    OrgMissing(String),
    /// Organization already exists.
    #[error("organization {0} already exists")]
    OrgExists(String),
    /// Organization invite could not be found.
    #[error("org invite not found: {0}")]
    OrgInviteNotFound(String),
    /// Organization invite has expired.
    #[error("org invite expired: {0}")]
    OrgInviteExpired(String),
    /// User is not a member of the organization.
    #[error("user {0} is not a member of organization {1}")]
    NotOrgMember(String, String),
    /// User lacks permission for this operation.
    #[error("permission denied: {0}")]
    PermissionDenied(String),
    /// Organization still has members and cannot be deleted.
    #[error("organization {0} is not empty")]
    OrgNotEmpty(String),
    /// A pending invite already exists for this email.
    #[error("pending invite already exists for {0}")]
    OrgInviteAlreadyPending(String),
    /// Email does not match the invite email.
    #[error("email mismatch: expected {expected}, got {actual}")]
    EmailMismatch {
        /// Expected email address.
        expected: String,
        /// Actual email address.
        actual: String,
    },
    /// User is already a member of the organization.
    #[error("user {0} is already a member of organization {1}")]
    AlreadyOrgMember(String, String),
    /// Invite has already been accepted.
    #[error("invite already accepted")]
    OrgInviteAlreadyAccepted,
    /// Invite has been revoked.
    #[error("invite has been revoked")]
    OrgInviteRevoked,
    /// Postgres returned an error.
    #[error("postgres error: {0}")]
    Postgres(tokio_postgres::Error),
}

impl From<deadpool::managed::builder::BuildError> for Error {}

impl From<deadpool::managed::errors::PoolError<tokio_postgres::Error>> for Error {}

impl From<password_hash::errors::Error> for Error {}

impl From<tokio_postgres::Error> for Error {}

/// Namespace status change returned after updating edge-visible namespace
/// state.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct NamespaceStatusUpdate {
    /// Namespace name used as the durable identity.
    pub name: String,
    /// Whether the namespace is suspended after the update.
    pub suspended: bool,
    /// Namespace generation after the update.
    pub r#gen: i64,
}

/// Detailed organization information.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct OrgDetail {
    /// Unique identifier for the organization.
    pub id: OrgId,
    /// Namespace ID for the organization.
    pub namespace_id: NamespaceId,
    /// Organization's unique name.
    pub name: String,
    /// Optional display name.
    pub display_name: Option<String>,
    /// User ID who created the organization, if the creator still exists.
    pub created_by: Option<UserId>,
    /// Namespace status for edge and admin views.
    pub namespace_status: String,
    /// Edge-visible namespace generation.
    pub namespace_gen: i64,
    /// When the organization was created.
    pub created_at: DateTime<Utc>,
    /// When the organization was last updated.
    pub updated_at: DateTime<Utc>,
}

/// Organization invite information.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct OrgInvite {
    /// Unique identifier for the invite.
    pub id: OrgInviteId,
    /// Organization ID the invite is for.
    pub org_id: OrgId,
    /// Email address invited.
    pub email: String,
    /// User ID who created the invite.
    pub invited_by: UserId,
    /// When the invite was created.
    pub created_at: DateTime<Utc>,
    /// When the invite expires.
    pub expires_at: DateTime<Utc>,
    /// When the invite was accepted, if ever.
    pub accepted_at: Option<DateTime<Utc>>,
    /// When the invite was revoked, if ever.
    pub revoked_at: Option<DateTime<Utc>>,
    /// User ID who accepted the invite, if accepted.
    pub accepted_by: Option<UserId>,
}

/// Organization membership information.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct OrgMember {
    /// User ID of the member.
    pub user_id: UserId,
    /// Username of the member.
    pub username: String,
    /// Email of the member.
    pub email: String,
    /// Role within the organization.
    pub role: OrgRole,
    /// User ID who added this member, if known.
    pub added_by: Option<UserId>,
    /// When the membership was created.
    pub created_at: DateTime<Utc>,
    /// When the membership was last updated.
    pub updated_at: DateTime<Utc>,
}

/// Organization summary information.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct OrgSummary {
    /// Unique identifier for the organization.
    pub id: OrgId,
    /// Namespace ID for the organization.
    pub namespace_id: NamespaceId,
    /// Organization's unique name.
    pub name: String,
    /// Optional display name.
    pub display_name: Option<String>,
    /// When the organization was created.
    pub created_at: DateTime<Utc>,
}

/// Parsed pagination cursor for list queries.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ParsedCursor {
    /// Timestamp component of the cursor.
    pub time: DateTime<Utc>,
    /// UUID component of the cursor.
    pub id: Uuid,
}

impl ParsedCursor {
    /// Parse a cursor string in the format "{created_at_iso}_{uuid}".
    #[must_use]
    pub fn parse(cursor: &str) -> Option<Self>;
}

/// Password hashing configuration used when storing new credentials.
#[derive(Clone, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct PasswordHashing {/* private fields */}

impl PasswordHashing {
    /// Hash a password using the configured parameters and a random salt.
    pub fn hash_password(&self, password: &str) -> crate::Result<String>;

    /// Use production-strength Argon2 parameters.
    #[must_use]
    pub fn production() -> Self;

    /// Use minimal Argon2 parameters suitable for unit tests.
    #[must_use]
    pub fn testing() -> Self;
}

/// Result type for Ankh database operations.
pub type Result<T> = Result<T, Error>;

/// Session metadata stored in the database.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct Session {
    /// Owning user email.
    pub email: String,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last touch timestamp.
    pub touched_at: DateTime<Utc>,
    /// Absolute expiry timestamp.
    pub expires_at: DateTime<Utc>,
}

/// Session status for filtering.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub enum SessionStatus {
    /// Session is active.
    Active,
    /// Session has been revoked.
    Revoked,
    /// Session has expired.
    Expired,
}

/// Summary session information for listing.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct SessionSummary {
    /// Unique identifier for the session.
    pub id: SessionId,
    /// User ID that owns this session.
    pub user_id: UserId,
    /// User email.
    pub user_email: String,
    /// When the session was created.
    pub created_at: DateTime<Utc>,
    /// When the session was last touched.
    pub touched_at: DateTime<Utc>,
    /// When the session expires.
    pub expires_at: DateTime<Utc>,
    /// When the session was revoked, if ever.
    pub revoked_at: Option<DateTime<Utc>>,
}

/// Sysadmin account metadata.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct SysadminInfo {
    /// Unique identifier for the sysadmin account.
    pub id: SysadminId,
    /// Sysadmin email address.
    pub email: String,
    /// When the sysadmin account was created.
    pub created_at: DateTime<Utc>,
    /// When the sysadmin last logged in, if ever.
    pub last_login_at: Option<DateTime<Utc>>,
    /// When the sysadmin account was disabled, if disabled.
    pub disabled_at: Option<DateTime<Utc>>,
}

/// Token purpose used for one-time identity actions.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub enum TokenKind {
    /// Email verification token created after signup.
    EmailVerification,
    /// Password reset token created by the forgot-password flow.
    PasswordReset,
}

impl TokenKind {
    /// Return the stable database storage value for this token kind.
    #[must_use]
    pub fn as_str(self) -> &'static str;
}

/// Detailed user information for admin viewing.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct UserDetail {
    /// Unique identifier for the user.
    pub id: UserId,
    /// User's namespace ID.
    pub namespace_id: NamespaceId,
    /// User's unique username.
    pub username: String,
    /// User email address.
    pub email: String,
    /// When the user account was created.
    pub created_at: DateTime<Utc>,
    /// When the email was verified, if ever.
    pub verified_at: Option<DateTime<Utc>>,
    /// Most recent session activity, if any sessions exist.
    pub last_session_at: Option<DateTime<Utc>>,
}

/// Summary user information for listing.
#[derive(
    Clone, Debug, Eq, PartialEq, swc_common::sync::single::Send, swc_common::sync::single::Sync,
)]
pub struct UserSummary {
    /// Unique identifier for the user.
    pub id: UserId,
    /// User's namespace ID.
    pub namespace_id: NamespaceId,
    /// User's unique username.
    pub username: String,
    /// User email address.
    pub email: String,
    /// When the user account was created.
    pub created_at: DateTime<Utc>,
    /// When the email was verified, if ever.
    pub verified_at: Option<DateTime<Utc>>,
}

/// Create a database pool for the provided connection string.
pub fn create_pg_pool(params: impl Into<String>) -> crate::Result<AnkhDbPool>;

/// Create a database pool with an explicit maximum size.
pub fn create_pg_pool_with_max_size(
    params: impl Into<String>,
    max_size: u32,
) -> crate::Result<AnkhDbPool>;

/// Create a database pool with an explicit maximum size and Ankh configuration.
pub fn create_pg_pool_with_max_size_and_config(
    params: impl Into<String>,
    max_size: u32,
    config: AnkhDbConfig,
) -> crate::Result<AnkhDbPool>;

/// Hash a raw secret for database storage.
///
/// Secrets are stored as lowercase hex-encoded SHA-256 digests to avoid leaking
/// raw values through database access.
#[must_use]
pub fn hash_secret(secret: &str) -> String;

/// Generate a cursor string from timestamp and ID.
#[must_use]
pub fn make_cursor(time: &DateTime<Utc>, id: &Uuid) -> String;

/// Canonical Ankh identity schema SQL.
///
/// Returned by function rather than exposed as a constant so the embedded SQL
/// does not pollute the rendered documentation.
#[must_use]
pub fn schema_sql() -> &'static str;

/// Current Ankh schema version inserted by [`crate::AnkhDb::initialize`].
pub const ANKH_SCHEMA_VERSION: i32 = 1;

pub mod test_support {
    //! Test database helpers for Ankh integration tests.

    /// Fresh Ankh test database passed to a test callback.
    #[derive(Clone, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
    pub struct FreshDb {/* private fields */}

    impl FreshDb {
        /// Return the generated database name.
        #[must_use]
        pub fn database_name(&self) -> &str;

        /// Fetch a pooled Ankh database connection.
        pub async fn get(&self) -> crate::Result<AnkhDb>;

        /// Return the pool connected to the generated database.
        #[must_use]
        pub fn pool(&self) -> &AnkhDbPool;
    }

    /// Configuration for creating fresh Ankh test databases.
    #[derive(
        Clone,
        Debug,
        Default,
        Eq,
        PartialEq,
        swc_common::sync::single::Send,
        swc_common::sync::single::Sync,
    )]
    pub struct FreshDbConfig {
        /// Postgres host.
        pub host: String,
        /// Postgres port.
        pub port: u16,
        /// Optional Postgres user. When absent, libpq's default user is used.
        pub user: Option<String>,
        /// Administrative database used to create and drop per-test databases.
        pub admin_database: String,
        /// Prefix for generated test database names.
        pub database_prefix: String,
    }

    /// Create a unique fresh database, seed it, run the callback, and drop it.
    pub async fn with_fresh_db<T, Seed, SeedFuture, Run, RunFuture>(
        seed: Seed,
        run: Run,
    ) -> crate::Result<T>
    where
        Run: FnOnce(FreshDb) -> RunFuture,
        RunFuture: Future<Output = crate::Result<T>>,
        Seed: FnOnce(AnkhDbPool) -> SeedFuture,
        SeedFuture: Future<Output = crate::Result<()>>;

    /// Create a configured fresh database, seed it, run the callback, and drop it.
    pub async fn with_fresh_db_with_config<T, Seed, SeedFuture, Run, RunFuture>(
        config: FreshDbConfig,
        seed: Seed,
        run: Run,
    ) -> crate::Result<T>
    where
        Run: FnOnce(FreshDb) -> RunFuture,
        RunFuture: Future<Output = crate::Result<T>>,
        Seed: FnOnce(AnkhDbPool) -> SeedFuture,
        SeedFuture: Future<Output = crate::Result<()>>;

    /// Default local database used for administrative test-database creation.
    pub const DEFAULT_ADMIN_DATABASE: &str = "postgres";

    /// Default local Postgres port reserved for Ankh tests.
    pub const DEFAULT_POSTGRES_PORT: u16 = 55_435;
}
