// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ankh-cli
// Publish: crates.io
// Workspace dependencies: ankh-types
// Workspace dependents: none
// Unnameable: crate::output::RenderTable

//! Shared command-line administration plumbing for Ankh consumers.

use std::{
    collections::HashMap,
    fmt::{Debug, Display},
    ops::Deref,
    path::{Path, PathBuf},
};

use ankh_types::admin::{
    AddMemberRequest, CreateOrgInviteRequest, CreateOrgInviteResponse, CreateOrgRequest,
    InviteUserResponse, ListDeviceSessionsResponse, ListMembersResponse, ListOrgInvitesResponse,
    ListOrgsResponse, ListSessionsResponse, ListSysadminsResponse, ListUsersResponse,
    LoginResponse, OrgDetail, ReleaseUserRequest, ReleaseUserResponse, SetRoleRequest,
    SettingsResponse, TransferOwnershipRequest, UpdateOrgRequest, UserDetail, WhoamiResponse,
};
use chrono::{DateTime, Utc};
use clap_builder::derive::{Args, FromArgMatches, Subcommand, ValueEnum};
use http::method::Method;
use inquire::InquireError;
use reqwest::async_impl::request::RequestBuilder;
use serde_core::{
    de::{Deserialize, DeserializeOwned},
    ser::Serialize,
};

/// Trait for types that can be rendered.
pub trait Render {
    /// Render the value in the specified format.
    fn render(&self, format: Format);

    /// Render the value to a string in the specified format.
    fn render_to_string(&self, format: Format) -> String;
}

impl<T: crate::output::RenderTable + Serialize> Render for T {}

/// Admin API client.
#[derive(swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct AdminClient {/* private fields */}

impl AdminClient {
    /// POST /admin/v1/orgs/:id/members
    pub async fn add_org_member(&self, id: &str, request: &AddMemberRequest) -> crate::Result<()>;

    /// DELETE /admin/v1/orgs/:org_id/invites/:invite_id
    pub async fn cancel_org_invite(&self, org_id: &str, invite_id: &str) -> crate::Result<()>;

    /// POST /admin/v1/orgs
    pub async fn create_org(&self, request: &CreateOrgRequest) -> crate::Result<OrgDetail>;

    /// POST /admin/v1/orgs/:id/invites
    pub async fn create_org_invite(
        &self,
        id: &str,
        request: &CreateOrgInviteRequest,
    ) -> crate::Result<CreateOrgInviteResponse>;

    /// DELETE /admin/v1/orgs/:id
    pub async fn delete_org(&self, id: &str) -> crate::Result<()>;

    /// DELETE /admin/v1/users/:id
    pub async fn delete_user(&self, id: &str) -> crate::Result<()>;

    /// Execute a request and parse the JSON response.
    pub async fn execute<T: DeserializeOwned>(&self, req: RequestBuilder) -> crate::Result<T>;

    /// Execute a request that returns no content (204).
    pub async fn execute_no_content(&self, req: RequestBuilder) -> crate::Result<()>;

    /// GET /admin/v1/orgs/:id
    pub async fn get_org(&self, id: &str) -> crate::Result<OrgDetail>;

    /// GET /admin/v1/settings
    pub async fn get_settings(&self) -> crate::Result<SettingsResponse>;

    /// GET /admin/v1/users/:id
    pub async fn get_user(&self, id: &str) -> crate::Result<UserDetail>;

    /// POST /admin/v1/users/invite
    pub async fn invite_user(&self, email: &str) -> crate::Result<InviteUserResponse>;

    /// GET /admin/v1/device-sessions
    pub async fn list_device_sessions(
        &self,
        params: &ListDeviceSessionsParams,
    ) -> crate::Result<ListDeviceSessionsResponse>;

    /// GET /admin/v1/orgs/:id/invites
    pub async fn list_org_invites(&self, id: &str) -> crate::Result<ListOrgInvitesResponse>;

    /// GET /admin/v1/orgs/:id/members
    pub async fn list_org_members(&self, id: &str) -> crate::Result<ListMembersResponse>;

    /// GET /admin/v1/orgs
    pub async fn list_orgs(&self, params: &ListOrgsParams) -> crate::Result<ListOrgsResponse>;

    /// GET /admin/v1/sessions
    pub async fn list_sessions(
        &self,
        params: &ListSessionsParams,
    ) -> crate::Result<ListSessionsResponse>;

    /// GET /admin/v1/sysadmins
    pub async fn list_sysadmins(
        &self,
        params: &ListSysadminsParams,
    ) -> crate::Result<ListSysadminsResponse>;

    /// GET /admin/v1/users
    pub async fn list_users(&self, params: &ListUsersParams) -> crate::Result<ListUsersResponse>;

    /// POST /admin/v1/auth/login
    pub async fn login(&self, email: &str, password: &str) -> crate::Result<LoginResponse>;

    /// Create a new admin client.
    pub fn new(base_url: impl Into<String>) -> Self;

    /// POST /admin/v1/users/release
    pub async fn release_user(
        &self,
        request: &ReleaseUserRequest,
    ) -> crate::Result<ReleaseUserResponse>;

    /// DELETE /admin/v1/orgs/:org_id/members/:user_id
    pub async fn remove_org_member(&self, org_id: &str, user_id: &str) -> crate::Result<()>;

    /// Build a request with common headers.
    pub fn request(&self, method: Method, path: &str) -> RequestBuilder;

    /// POST /admin/v1/device-sessions/:id/revoke
    pub async fn revoke_device_session(&self, id: &str) -> crate::Result<()>;

    /// POST /admin/v1/sessions/:id/revoke
    pub async fn revoke_session(&self, id: &str) -> crate::Result<()>;

    /// PATCH /admin/v1/orgs/:org_id/members/:user_id
    pub async fn set_member_role(
        &self,
        org_id: &str,
        user_id: &str,
        request: &SetRoleRequest,
    ) -> crate::Result<()>;

    /// POST /admin/v1/settings/waitlist
    pub async fn set_waitlist_enabled(&self, enabled: bool) -> crate::Result<SettingsResponse>;

    /// POST /admin/v1/orgs/:id/transfer
    pub async fn transfer_org_ownership(
        &self,
        id: &str,
        request: &TransferOwnershipRequest,
    ) -> crate::Result<()>;

    /// PATCH /admin/v1/orgs/:id
    pub async fn update_org(&self, id: &str, request: &UpdateOrgRequest) -> crate::Result<()>;

    /// GET /admin/v1/sysadmins/me
    pub async fn whoami(&self) -> crate::Result<WhoamiResponse>;

    /// Set the bearer token for authentication.
    pub fn with_token(self, token: impl Into<String>) -> Self;

    /// Set the trace ID for request correlation.
    pub fn with_trace_id(self, trace_id: impl Into<String>) -> Self;
}

/// Authentication commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum AuthCommand {
    /// Log in to the admin API.
    Login {
        /// Base URL for the admin API.
        #[arg(long)]
        base_url: Option<String>,
        /// Email address for authentication (optional; prompts if omitted).
        #[arg(long)]
        email: Option<String>,
        /// Password for authentication (optional; prompts if omitted).
        #[arg(long)]
        password: Option<String>,
    },
    /// Display the authenticated sysadmin identity.
    Whoami,
}

impl FromArgMatches for AuthCommand {}

impl Subcommand for AuthCommand {}

/// Common top-level commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum CommonCommand {
    /// Authentication commands.
    Auth {
        /// Subcommand to run.
        #[command(subcommand)]
        command: AuthCommand,
    },
    /// User management commands.
    Users {
        /// Subcommand to run.
        #[command(subcommand)]
        command: UsersCommand,
    },
    /// Session management commands.
    Sessions {
        /// Subcommand to run.
        #[command(subcommand)]
        command: SessionsCommand,
    },
    /// Device session management commands.
    DeviceSessions {
        /// Subcommand to run.
        #[command(subcommand)]
        command: DeviceSessionsCommand,
    },
    /// Sysadmin account commands.
    Sysadmins {
        /// Subcommand to run.
        #[command(subcommand)]
        command: SysadminsCommand,
    },
    /// Global settings commands.
    Settings {
        /// Subcommand to run.
        #[command(subcommand)]
        command: SettingsCommand,
    },
    /// Organization management commands.
    Orgs {
        /// Subcommand to run.
        #[command(subcommand)]
        command: OrgsCommand,
    },
}

impl FromArgMatches for CommonCommand {}

impl Subcommand for CommonCommand {}

/// Shared runtime used by common command handlers.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct CommonRuntime {/* private fields */}

impl CommonRuntime {
    /// Resolve the config path for this invocation.
    pub fn config_path(&self) -> crate::Result<PathBuf>;

    /// Load config for this invocation and return the config path used.
    pub fn load_config(&self) -> crate::Result<(Config, PathBuf)>;

    /// Build a shared runtime.
    #[must_use]
    pub fn new(product: ProductInfo, args: GlobalArgs) -> Self;

    /// Return the product metadata.
    #[must_use]
    pub const fn product(&self) -> ProductInfo;
}

impl Deref for CommonRuntime {
    type Target = GlobalArgs;
}

/// Configuration file structure.
#[derive(Debug, Default, Deserialize<'de>, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct Config {
    /// Default profile name to use.
    #[serde(default)]
    pub default_profile: Option<String>,
    /// Named profiles.
    #[serde(default, rename = "profile")]
    pub profiles: HashMap<String, Profile>,
}

impl Config {
    /// Get a mutable profile by name, or create it if it doesn't exist.
    pub fn get_or_create_profile(&mut self, name: &str, base_url: &str) -> &mut Profile;

    /// Get a profile by name, or the default profile if no name is specified.
    pub fn get_profile<'a>(&self, name: Option<&'a str>) -> crate::Result<(&'a str, &'a Profile)>;

    /// Load config from an explicit path, creating an empty config if it
    /// doesn't exist.
    pub fn load_from_path(path: &Path) -> crate::Result<Self>;

    /// Returns the default config file path for a product config filename.
    pub fn path(filename: &str) -> crate::Result<PathBuf>;

    /// Save config to an explicit path.
    pub fn save_to_path(&self, path: &Path) -> crate::Result<()>;

    /// Set the default profile.
    pub fn set_default_profile(&mut self, name: &str);
}

/// Device session management commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum DeviceSessionsCommand {
    /// List device sessions.
    List {
        /// Pagination controls.
        #[command(flatten)]
        list: ListArgs,
        /// Filter by user ID.
        #[arg(long)]
        user_id: Option<String>,
        /// Filter by status (active, revoked, expired).
        #[arg(long)]
        status: Option<String>,
    },
    /// Revoke a device session.
    Revoke {
        /// Device session ID.
        id: String,
    },
}

impl FromArgMatches for DeviceSessionsCommand {}

impl Subcommand for DeviceSessionsCommand {}

/// CLI error type.
#[derive(
    Debug,
    Display,
    std::error::Error,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub enum Error {
    /// Configuration error.
    #[error("configuration error: {0}")]
    Config(String),
    /// No profile configured.
    #[error("no profile configured. Run `auth login` first")]
    NoProfile,
    /// Profile not found.
    #[error("profile '{0}' not found")]
    ProfileNotFound(String),
    /// Token expired.
    #[error("token expired. Run `auth login` to re-authenticate")]
    TokenExpired,
    /// HTTP request error.
    #[error("request error: {0}")]
    Request(reqwest::Error),
    /// API error response.
    #[error("{message}")]
    Api {
        /// HTTP status code.
        status: u16,
        /// Error code from API.
        code: String,
        /// Error message from API.
        message: String,
    },
    /// IO error.
    #[error("io error: {0}")]
    Io(std::io::Error),
    /// TOML parse error.
    #[error("config parse error: {0}")]
    TomlParse(toml::de::error::Error),
    /// TOML serialize error.
    #[error("config write error: {0}")]
    TomlSerialize(toml::ser::error::Error),
    /// JSON error.
    #[error("json error: {0}")]
    Json(serde_json::Error),
    /// Response body could not be decoded.
    #[error("invalid response: {0}")]
    InvalidResponse(String),
    /// Prompt error.
    #[error("prompt error: {0}")]
    Prompt(InquireError),
}

impl From<InquireError> for Error {}

impl From<reqwest::Error> for Error {}

impl From<serde_json::Error> for Error {}

impl From<std::io::Error> for Error {}

impl From<toml::de::error::Error> for Error {}

impl From<toml::ser::error::Error> for Error {}

/// Output format.
#[derive(
    Clone,
    Copy,
    Debug,
    Default,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub enum Format {
    /// Table output (default).
    #[default]
    Table,
    /// JSON output.
    Json,
}

impl ValueEnum for Format {}

/// Global options shared across Ankh-consuming admin CLIs.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct GlobalArgs {
    /// Base URL for the admin API (overrides config).
    #[arg(long, global = true)]
    pub base_url: Option<String>,
    /// Output format.
    #[arg(long, global = true, default_value = "table")]
    pub format: Format,
    /// Path to the CLI config file.
    #[arg(long = "config", global = true)]
    pub config_path: Option<PathBuf>,
    /// Profile to use.
    #[arg(long, global = true)]
    pub profile: Option<String>,
    /// Suppress non-essential output.
    #[arg(long, short, global = true)]
    pub quiet: bool,
    /// Emit verbose connection details.
    #[arg(long, short, global = true)]
    pub verbose: bool,
    /// Request trace ID for correlation.
    #[arg(long, global = true)]
    pub trace_id: Option<String>,
}

impl GlobalArgs {
    /// Convert common flags into an executable shared runtime.
    #[must_use]
    pub fn into_runtime(self, product: ProductInfo) -> CommonRuntime;
}

impl Args for GlobalArgs {}

impl FromArgMatches for GlobalArgs {}

/// Shared arguments for list commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ListArgs {
    /// Maximum number of items to return.
    #[arg(long, default_value = "50")]
    pub limit: i64,
    /// Pagination cursor.
    #[arg(long)]
    pub cursor: Option<String>,
}

impl Args for ListArgs {}

impl FromArgMatches for ListArgs {}

/// Parameters for listing device sessions.
#[derive(Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ListDeviceSessionsParams {
    /// Maximum number of sessions to return.
    pub limit: Option<i64>,
    /// Pagination cursor.
    pub cursor: Option<String>,
    /// Filter by user ID.
    pub user_id: Option<String>,
    /// Filter by status.
    pub status: Option<String>,
}

/// Parameters for listing organizations.
#[derive(Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ListOrgsParams {
    /// Maximum number of orgs to return.
    pub limit: Option<i64>,
    /// Pagination cursor.
    pub cursor: Option<String>,
}

/// Parameters for listing sessions.
#[derive(Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ListSessionsParams {
    /// Maximum number of sessions to return.
    pub limit: Option<i64>,
    /// Pagination cursor.
    pub cursor: Option<String>,
    /// Filter by user ID.
    pub user_id: Option<String>,
    /// Filter by status.
    pub status: Option<String>,
}

/// Parameters for listing sysadmins.
#[derive(Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ListSysadminsParams {
    /// Maximum number of sysadmins to return.
    pub limit: Option<i64>,
    /// Pagination cursor.
    pub cursor: Option<String>,
}

/// Parameters for listing users.
#[derive(Debug, Default, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct ListUsersParams {
    /// Maximum number of users to return.
    pub limit: Option<i64>,
    /// Pagination cursor.
    pub cursor: Option<String>,
    /// Email filter.
    pub email: Option<String>,
}

/// Organization invite commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum OrgInvitesCommand {
    /// List pending organization invites.
    List {
        /// Organization ID.
        org_id: String,
    },
    /// Create an organization invite.
    Create {
        /// Organization ID.
        org_id: String,
        /// Email to invite.
        #[arg(long)]
        email: String,
    },
    /// Cancel an organization invite.
    Cancel {
        /// Organization ID.
        org_id: String,
        /// Invite ID.
        invite_id: String,
        /// Skip confirmation prompt.
        #[arg(long, short)]
        yes: bool,
    },
}

impl FromArgMatches for OrgInvitesCommand {}

impl Subcommand for OrgInvitesCommand {}

/// Organization member commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum OrgMembersCommand {
    /// List organization members.
    List {
        /// Organization ID.
        org_id: String,
    },
    /// Add a member to an organization.
    Add {
        /// Organization ID.
        org_id: String,
        /// User ID to add.
        #[arg(long)]
        user_id: String,
        /// Role for the new member (admin or member).
        #[arg(long, default_value = "member")]
        role: String,
    },
    /// Remove a member from an organization.
    Remove {
        /// Organization ID.
        org_id: String,
        /// User ID to remove.
        user_id: String,
        /// Skip confirmation prompt.
        #[arg(long, short)]
        yes: bool,
    },
    /// Set a member's role.
    SetRole {
        /// Organization ID.
        org_id: String,
        /// User ID.
        user_id: String,
        /// New role (admin or member).
        #[arg(long)]
        role: String,
    },
}

impl FromArgMatches for OrgMembersCommand {}

impl Subcommand for OrgMembersCommand {}

/// Organization management commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum OrgsCommand {
    /// List organizations.
    List {
        /// Pagination controls.
        #[command(flatten)]
        list: ListArgs,
    },
    /// Get organization details.
    Get {
        /// Organization ID.
        id: String,
    },
    /// Create an organization.
    Create {
        /// Organization name (namespace).
        name: String,
        /// Display name.
        #[arg(long)]
        display_name: Option<String>,
        /// Owner user ID.
        #[arg(long)]
        owner_id: String,
    },
    /// Update an organization.
    Update {
        /// Organization ID.
        id: String,
        /// Display name.
        #[arg(long)]
        display_name: Option<String>,
    },
    /// Delete an organization.
    Remove {
        /// Organization ID.
        id: String,
        /// Skip confirmation prompt.
        #[arg(long, short)]
        yes: bool,
    },
    /// Member management commands.
    Members {
        /// Subcommand to run.
        #[command(subcommand)]
        command: OrgMembersCommand,
    },
    /// Invite management commands.
    Invites {
        /// Subcommand to run.
        #[command(subcommand)]
        command: OrgInvitesCommand,
    },
    /// Transfer organization ownership.
    Transfer {
        /// Organization ID.
        id: String,
        /// New owner's user ID.
        #[arg(long)]
        new_owner_id: String,
        /// Skip confirmation prompt.
        #[arg(long, short)]
        yes: bool,
    },
}

impl FromArgMatches for OrgsCommand {}

impl Subcommand for OrgsCommand {}

/// Product-specific CLI configuration supplied by leaf CLIs.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    swc_common::sync::single::Send,
    swc_common::sync::single::Sync,
)]
pub struct ProductInfo {/* private fields */}

impl ProductInfo {
    /// Return the binary name.
    #[must_use]
    pub const fn binary_name(self) -> &'static str;

    /// Return the default config filename.
    #[must_use]
    pub const fn config_filename(self) -> &'static str;

    /// Return the default base URL.
    #[must_use]
    pub const fn default_base_url(self) -> &'static str;

    /// Build product metadata using the common local development base URL.
    #[must_use]
    pub const fn new(binary_name: &'static str, config_filename: &'static str) -> Self;

    /// Build product metadata with an explicit default base URL.
    #[must_use]
    pub const fn with_default_base_url(
        binary_name: &'static str,
        config_filename: &'static str,
        default_base_url: &'static str,
    ) -> Self;
}

/// A named profile with connection settings.
#[derive(Clone, Debug, Deserialize<'de>, Serialize, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub struct Profile {
    /// Base URL for the admin API (e.g., "http://localhost:8080").
    pub base_url: String,
    /// Bearer token for authentication.
    #[serde(default)]
    pub token: Option<String>,
    /// Token expiration time.
    #[serde(default)]
    pub token_expires_at: Option<DateTime<Utc>>,
}

impl Profile {
    /// Get the token, returning an error if expired or missing.
    pub fn get_token(&self) -> crate::Result<&str>;
}

/// CLI result type.
pub type Result<T> = Result<T, Error>;

/// Session management commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum SessionsCommand {
    /// List sessions.
    List {
        /// Pagination controls.
        #[command(flatten)]
        list: ListArgs,
        /// Filter by user ID.
        #[arg(long)]
        user_id: Option<String>,
        /// Filter by status (active, revoked, expired).
        #[arg(long)]
        status: Option<String>,
    },
    /// Revoke a session.
    Revoke {
        /// Session ID.
        id: String,
    },
}

impl FromArgMatches for SessionsCommand {}

impl Subcommand for SessionsCommand {}

/// Settings commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum SettingsCommand {
    /// Waitlist settings.
    Waitlist {
        /// Subcommand to run.
        #[command(subcommand)]
        command: WaitlistCommand,
    },
}

impl FromArgMatches for SettingsCommand {}

impl Subcommand for SettingsCommand {}

/// Sysadmin account commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum SysadminsCommand {
    /// List sysadmin accounts.
    List {
        /// Pagination controls.
        #[command(flatten)]
        list: ListArgs,
    },
}

impl FromArgMatches for SysadminsCommand {}

impl Subcommand for SysadminsCommand {}

/// User management commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum UsersCommand {
    /// List users.
    List {
        /// Pagination controls.
        #[command(flatten)]
        list: ListArgs,
        /// Filter by email.
        #[arg(long)]
        email: Option<String>,
    },
    /// Get user details.
    Get {
        /// User ID.
        id: String,
    },
    /// Delete a user.
    Remove {
        /// User ID.
        id: String,
        /// Skip confirmation prompt.
        #[arg(long, short)]
        yes: bool,
    },
    /// Release a waitlisted user.
    Release {
        /// User email or ID.
        target: String,
    },
    /// Invite a user and bypass the waitlist.
    Invite {
        /// User email.
        email: String,
    },
}

impl FromArgMatches for UsersCommand {}

impl Subcommand for UsersCommand {}

/// Waitlist settings commands.
#[derive(Clone, Debug, swc_common::sync::single::Send, swc_common::sync::single::Sync)]
pub enum WaitlistCommand {
    /// Show current waitlist setting.
    Status,
    /// Enable waitlist mode.
    Enable,
    /// Disable waitlist mode.
    Disable,
}

impl FromArgMatches for WaitlistCommand {}

impl Subcommand for WaitlistCommand {}

/// Build an authenticated admin client based on runtime configuration.
pub fn get_client(runtime: &CommonRuntime) -> crate::Result<AdminClient>;

/// Print a message if not in quiet mode.
pub fn info(quiet: bool, msg: &str);

/// Print pagination info.
pub fn print_cursor(cursor: Option<&str>, quiet: bool);

/// Execute a common command with the provided runtime configuration.
pub async fn run_common(runtime: CommonRuntime, command: CommonCommand) -> crate::Result<()>;
